// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInstallDisplayName = `-- name: GetInstallDisplayName :one
SELECT display_name
FROM install_identity
WHERE id = 1
`

// One-shot read at the top of every eval cycle; the workers cache the
// result locally for the cycle's per-fire payload assembly.
func (q *Queries) GetInstallDisplayName(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getInstallDisplayName)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const getLatestDailyForMP = `-- name: GetLatestDailyForMP :one
SELECT
    bucket,
    metering_point_id,
    avg_instant,
    cumulative_delta AS sum_consumption
FROM measurement_daily
WHERE metering_point_id = $1
ORDER BY bucket DESC
LIMIT 1
`

type GetLatestDailyForMPRow struct {
	Bucket          interface{}
	MeteringPointID pgtype.UUID
	AvgInstant      float64
	SumConsumption  int64
}

// ThresholdDailyWorker reads the most-recent 1-day bucket from the
// measurement_daily continuous aggregate (0026). cumulative_delta is the
// day's total consumption — the breach metric for "daily total > N".
func (q *Queries) GetLatestDailyForMP(ctx context.Context, meteringPointID pgtype.UUID) (GetLatestDailyForMPRow, error) {
	row := q.db.QueryRow(ctx, getLatestDailyForMP, meteringPointID)
	var i GetLatestDailyForMPRow
	err := row.Scan(
		&i.Bucket,
		&i.MeteringPointID,
		&i.AvgInstant,
		&i.SumConsumption,
	)
	return i, err
}

const getLatestHourlyForMP = `-- name: GetLatestHourlyForMP :one
SELECT
    bucket,
    metering_point_id,
    avg_instant,
    cumulative_delta AS sum_consumption
FROM measurement_hourly
WHERE metering_point_id = $1
ORDER BY bucket DESC
LIMIT 1
`

type GetLatestHourlyForMPRow struct {
	Bucket          interface{}
	MeteringPointID pgtype.UUID
	AvgInstant      float64
	SumConsumption  int32
}

// ThresholdHourlyWorker reads the most-recent 1-hour bucket from the
// measurement_hourly continuous aggregate (0025). avg_instant is what the
// rule's bound is compared against (a meter "averaged above threshold"
// semantic) — sum_consumption is reported in the payload but is not the
// breach metric.
func (q *Queries) GetLatestHourlyForMP(ctx context.Context, meteringPointID pgtype.UUID) (GetLatestHourlyForMPRow, error) {
	row := q.db.QueryRow(ctx, getLatestHourlyForMP, meteringPointID)
	var i GetLatestHourlyForMPRow
	err := row.Scan(
		&i.Bucket,
		&i.MeteringPointID,
		&i.AvgInstant,
		&i.SumConsumption,
	)
	return i, err
}

const getLatestMeasurementForMP = `-- name: GetLatestMeasurementForMP :one
SELECT
    time,
    metering_point_id,
    instant_value,
    cumulative_value
FROM measurement
WHERE metering_point_id = $1
ORDER BY time DESC
LIMIT 1
`

type GetLatestMeasurementForMPRow struct {
	Time            pgtype.Timestamptz
	MeteringPointID pgtype.UUID
	InstantValue    pgtype.Numeric
	CumulativeValue pgtype.Numeric
}

// ThresholdInstantaneousWorker pulls the most-recent uplink and compares
// instant_value against the rule's bound(s). The (metering_point_id,
// time DESC) hot-path index on `measurement` (0015) makes this an
// index scan + LIMIT 1.
func (q *Queries) GetLatestMeasurementForMP(ctx context.Context, meteringPointID pgtype.UUID) (GetLatestMeasurementForMPRow, error) {
	row := q.db.QueryRow(ctx, getLatestMeasurementForMP, meteringPointID)
	var i GetLatestMeasurementForMPRow
	err := row.Scan(
		&i.Time,
		&i.MeteringPointID,
		&i.InstantValue,
		&i.CumulativeValue,
	)
	return i, err
}

const getMeteringPointLabel = `-- name: GetMeteringPointLabel :one
SELECT
    id,
    name AS label
FROM metering_point
WHERE id = $1
`

type GetMeteringPointLabelRow struct {
	ID    pgtype.UUID
	Label string
}

// expandScope() helper for metering_point-scoped rules: load the MP label
// so the payload's target.label field is populated for the alert center.
func (q *Queries) GetMeteringPointLabel(ctx context.Context, id pgtype.UUID) (GetMeteringPointLabelRow, error) {
	row := q.db.QueryRow(ctx, getMeteringPointLabel, id)
	var i GetMeteringPointLabelRow
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const listAllActiveMeteringPoints = `-- name: ListAllActiveMeteringPoints :many
SELECT
    id,
    name AS label
FROM metering_point
WHERE archived_at IS NULL
ORDER BY id
`

type ListAllActiveMeteringPointsRow struct {
	ID    pgtype.UUID
	Label string
}

// expandScope() helper for global-scoped rules.
func (q *Queries) ListAllActiveMeteringPoints(ctx context.Context) ([]ListAllActiveMeteringPointsRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveMeteringPoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActiveMeteringPointsRow
	for rows.Next() {
		var i ListAllActiveMeteringPointsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHysteresisClearOffline = `-- name: ListHysteresisClearOffline :many
SELECT
    a.id        AS alert_id,
    d.id        AS device_id,
    a.rule_id   AS rule_id
FROM alert a
JOIN device d           ON a.target_entity_id = d.id
JOIN device_profile dp  ON d.device_profile_id = dp.id
WHERE a.state = 'firing'
  AND a.rule_kind = 'offline_device'
  AND d.last_seen_at IS NOT NULL
  AND now() - d.last_seen_at < make_interval(secs => 2 * dp.expected_interval_s)
`

type ListHysteresisClearOfflineRow struct {
	AlertID  pgtype.UUID
	DeviceID pgtype.UUID
	RuleID   pgtype.UUID
}

// D-15 hysteresis: devices currently 'firing' an offline alert whose
// last_uplink is back inside 2× expected_interval — those clear.
//
// Compared to D-15's STRICTER fire threshold (3×), the clear threshold is
// LOOSER (<2×) so a device that just barely recovered does not immediately
// re-fire on the next cycle if its uplinks bounce back into the 2×–3× band.
func (q *Queries) ListHysteresisClearOffline(ctx context.Context) ([]ListHysteresisClearOfflineRow, error) {
	rows, err := q.db.Query(ctx, listHysteresisClearOffline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHysteresisClearOfflineRow
	for rows.Next() {
		var i ListHysteresisClearOfflineRow
		if err := rows.Scan(&i.AlertID, &i.DeviceID, &i.RuleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeteringPointsBySite = `-- name: ListMeteringPointsBySite :many
SELECT
    id,
    name AS label
FROM metering_point
WHERE site_id = $1
  AND archived_at IS NULL
ORDER BY id
`

type ListMeteringPointsBySiteRow struct {
	ID    pgtype.UUID
	Label string
}

// expandScope() helper for site-scoped rules — returns MP ids + labels
// ordered for deterministic iteration in tests.
func (q *Queries) ListMeteringPointsBySite(ctx context.Context, siteID pgtype.UUID) ([]ListMeteringPointsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listMeteringPointsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeteringPointsBySiteRow
	for rows.Next() {
		var i ListMeteringPointsBySiteRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfflineDevicesWithGatewayStatus = `-- name: ListOfflineDevicesWithGatewayStatus :many

SELECT
    d.id                                              AS device_id,
    d.name                                            AS device_label,
    d.last_seen_at                                    AS last_uplink_at,
    dp.expected_interval_s                            AS expected_interval_s,
    g.id                                              AS gateway_id,
    g.name                                            AS gateway_label,
    g.last_seen_at                                    AS gateway_last_seen_at,
    (
        g.id IS NOT NULL
        AND g.last_seen_at IS NOT NULL
        AND now() - g.last_seen_at > make_interval(secs => 3 * dp.expected_interval_s)
    )                                                 AS gateway_offline
FROM device d
JOIN device_profile dp ON d.device_profile_id = dp.id
LEFT JOIN gateway g    ON d.gateway_id = g.id
WHERE d.decommissioned_at IS NULL
  AND d.last_seen_at IS NOT NULL
  AND now() - d.last_seen_at > make_interval(secs => 3 * dp.expected_interval_s)
`

type ListOfflineDevicesWithGatewayStatusRow struct {
	DeviceID          pgtype.UUID
	DeviceLabel       string
	LastUplinkAt      pgtype.Timestamptz
	ExpectedIntervalS int32
	GatewayID         pgtype.UUID
	GatewayLabel      *string
	GatewayLastSeenAt pgtype.Timestamptz
	GatewayOffline    *bool
}

// Alerts — Phase 6 Plan 06-02 threshold + offline evaluator queries.
//
// D-12 payload shape is built in Go (internal/alert/payload.go) — these
// queries are the data sources the workers feed into BuildPayload.
//
// Schema note (06-02 Rule 3 deviation): the Phase 2 schema names columns
// differently than the 06-RESEARCH SQL did — these queries use the actual
// column names (`device.name` not `device.label`, `device.last_seen_at`
// not `last_uplink_at`, `device.device_profile_id` not `profile_id`,
// `device.decommissioned_at` not `disabled_at`). Migration 0045 added
// `device.gateway_id` + `gateway.last_seen_at` to satisfy ALERT-03.
// D-15 + D-14: returns device-offline candidates AND a gateway-offline flag
// per-row. Worker uses the flag to suppress device alerts behind downed
// gateways and to emit a single gateway-offline alert.
//
// The single LEFT JOIN keeps this an O(active-devices) query — without it
// the worker would N+1-fetch gateway last_seen_at per row. The boolean
// expression for gateway_offline mirrors D-15's 3× threshold (i.e. a
// gateway is "offline" when it has been silent for 3 × the device's
// expected interval — same yardstick the device uses).
func (q *Queries) ListOfflineDevicesWithGatewayStatus(ctx context.Context) ([]ListOfflineDevicesWithGatewayStatusRow, error) {
	rows, err := q.db.Query(ctx, listOfflineDevicesWithGatewayStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfflineDevicesWithGatewayStatusRow
	for rows.Next() {
		var i ListOfflineDevicesWithGatewayStatusRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.DeviceLabel,
			&i.LastUplinkAt,
			&i.ExpectedIntervalS,
			&i.GatewayID,
			&i.GatewayLabel,
			&i.GatewayLastSeenAt,
			&i.GatewayOffline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
