// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEntriesByAction = `-- name: CountAuditEntriesByAction :one
SELECT count(*) FROM audit_log WHERE action = $1 AND time >= $2
`

type CountAuditEntriesByActionParams struct {
	Action string
	Time   pgtype.Timestamptz
}

// Phase 6 metrics tile + Phase 2 tests. Time-bounded so the tile can show
// "X swaps in the last 7 days" without scanning the whole table.
func (q *Queries) CountAuditEntriesByAction(ctx context.Context, arg CountAuditEntriesByActionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntriesByAction, arg.Action, arg.Time)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditEntry = `-- name: GetAuditEntry :one
SELECT id, time, user_id, action, entity_type, entity_id, before, after, notes, request_id FROM audit_log WHERE id = $1
`

// Test-only in Phase 2 (the round-trip assertion in measurements_test.go's
// audit sibling). Phase 6 audit browse will use ListAuditEntriesByEntity +
// pagination instead.
func (q *Queries) GetAuditEntry(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditEntry, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Notes,
		&i.RequestID,
	)
	return i, err
}

const listAuditEntriesByEntity = `-- name: ListAuditEntriesByEntity :many
SELECT id, time, user_id, action, entity_type, entity_id, before, after, notes, request_id FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY time DESC
LIMIT $3 OFFSET $4
`

type ListAuditEntriesByEntityParams struct {
	EntityType string
	EntityID   pgtype.UUID
	Limit      int32
	Offset     int32
}

// Phase 6 audit browse with entity filter ("show me everything that ever
// happened to MP <id>"). Phase 2 ships the query so internal tests can
// assert WriteEntry actually persisted what was claimed. Bounded by LIMIT/
// OFFSET so a UI can't accidentally page through years of audit rows.
func (q *Queries) ListAuditEntriesByEntity(ctx context.Context, arg ListAuditEntriesByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Notes,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesByUser = `-- name: ListAuditEntriesByUser :many
SELECT id, time, user_id, action, entity_type, entity_id, before, after, notes, request_id FROM audit_log
WHERE user_id = $1
ORDER BY time DESC
LIMIT $2 OFFSET $3
`

type ListAuditEntriesByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

// Phase 6 "all actions by Alice" browse. The (user_id, time DESC) index
// (0016) covers this directly.
func (q *Queries) ListAuditEntriesByUser(ctx context.Context, arg ListAuditEntriesByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Notes,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditLog = `-- name: WriteAuditLog :exec

INSERT INTO audit_log (
    user_id, action, entity_type, entity_id,
    before, after, notes, request_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type WriteAuditLogParams struct {
	UserID     pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	Before     []byte
	After      []byte
	Notes      *string
	RequestID  *string
}

// Audit Log (D-22 + D-23 + D-24 + AUDIT-01). The audit_log table is
// INSERT-ONLY at the DB layer (0016 trigger raises `audit_log is INSERT-ONLY`
// on UPDATE / DELETE — T-02-04-02 mitigation). Every state-changing action on
// Site, Metering Point, Device, Device Profile, and Binding writes a row
// here in the SAME transaction as the domain mutation (D-23, Pitfall 7).
//
// Plan 02-08 wraps WriteAuditLog in `internal/audit/log.go` with an Entry
// struct + audit.WriteEntry(ctx, tx, entry) helper that takes a pgx.Tx
// (NOT a Pool) — call sites pass the same tx the domain mutation uses so
// the audit row commits atomically with the change it describes.
// D-22 + D-23: 8 caller-provided fields (id auto-generated by
// gen_random_uuid() default, time auto by now() default).
// The CHECK constraints enforce D-22 vocabulary at the DB layer:
//
//	action ∈ {create, update, archive, restore, swap, decommission,
//	          profile_create, profile_update, binding_open, binding_close,
//	          rollover_detected}
//	entity_type ∈ {site, metering_point, device, device_profile, binding}
//
// An action / entity_type outside these sets raises 23514 (check_violation)
// with the named CHECK constraint in the error — caller treats as a bug.
func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Notes,
		arg.RequestID,
	)
	return err
}
