// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceReadingOffset = `-- name: AdvanceReadingOffset :exec
UPDATE binding SET reading_offset = reading_offset + $2 WHERE id = $1
`

type AdvanceReadingOffsetParams struct {
	ID            pgtype.UUID
	ReadingOffset pgtype.Numeric
}

// DATA-05 rollover handler: when raw_value at time t < last_raw_value at
// time t-1 AND the gap is plausibly a counter wrap (not a swap), advance
// the offset by counter_modulus so cumulative_value stays monotonic.
// $2 = device_profile.counter_modulus (NUMERIC) — caller passes the value
// it already loaded for the resolver.
func (q *Queries) AdvanceReadingOffset(ctx context.Context, arg AdvanceReadingOffsetParams) error {
	_, err := q.db.Exec(ctx, advanceReadingOffset, arg.ID, arg.ReadingOffset)
	return err
}

const closeBinding = `-- name: CloseBinding :one
UPDATE binding SET valid_to = $2
WHERE id = $1 AND valid_to IS NULL
RETURNING id, metering_point_id, device_id, valid_from, valid_to, reading_offset, last_raw_value, created_at
`

type CloseBindingParams struct {
	ID      pgtype.UUID
	ValidTo pgtype.Timestamptz
}

// D-14: valid_to = swap.confirm_time (operator click) — the closing side of
// a swap. Idempotent guard: only closes a still-open binding.
func (q *Queries) CloseBinding(ctx context.Context, arg CloseBindingParams) (Binding, error) {
	row := q.db.QueryRow(ctx, closeBinding, arg.ID, arg.ValidTo)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ReadingOffset,
		&i.LastRawValue,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveBindingByDevEUI = `-- name: GetActiveBindingByDevEUI :one

SELECT b.id, b.metering_point_id, b.device_id, b.valid_from, b.valid_to,
       b.reading_offset, b.last_raw_value,
       d.dev_eui,
       dp.id AS device_profile_id,
       dp.counter_modulus
FROM binding b
JOIN device          d  ON d.id = b.device_id
JOIN device_profile  dp ON dp.id = d.device_profile_id
WHERE d.dev_eui = $1
  AND b.valid_from <= $2
  AND (b.valid_to IS NULL OR b.valid_to > $2)
LIMIT 1
`

type GetActiveBindingByDevEUIParams struct {
	DevEui    string
	ValidFrom pgtype.Timestamptz
}

type GetActiveBindingByDevEUIRow struct {
	ID              pgtype.UUID
	MeteringPointID pgtype.UUID
	DeviceID        pgtype.UUID
	ValidFrom       pgtype.Timestamptz
	ValidTo         pgtype.Timestamptz
	ReadingOffset   pgtype.Numeric
	LastRawValue    pgtype.Numeric
	DevEui          string
	DeviceProfileID pgtype.UUID
	CounterModulus  int64
}

// Binding (DATA-02 + D-14 + D-15 + D-25). Each device-to-MP binding has a
// half-open [valid_from, valid_to) window (Open Q #1 resolution: tstzrange
// '[)' bounds — a swap at exactly t=valid_to attributes that uplink to the
// NEW binding).
//
// The 0014 EXCLUDE constraints (binding_no_overlap_per_mp +
// binding_no_overlap_per_device) make at most one active binding per MP
// AND per device — so OpenBinding is race-safe (concurrent commits get
// 23P01 and the loser retries).
// D-25 RESOLVER HOT-PATH: dev_eui → metering_point_id at uplink time.
// Verbatim from 02-RESEARCH §"sqlc query for find active binding for dev_eui
// at time T". Returns one denormalized row joining binding + device +
// device_profile so the resolver doesn't need three SELECTs in Go code.
//
// $1 = dev_eui (lowercase 16-hex), $2 = uplink time (TIMESTAMPTZ — typically
// gateway_rx_time, but resolver may also probe historical state by passing
// an older timestamp). Half-open window per Open Q #1: valid_from <= t AND
// (valid_to IS NULL OR valid_to > t).
//
// The btree_gist EXCLUDE on binding guarantees ≤1 row matches; LIMIT 1 is
// defensive against a hypothetical constraint violation rather than the
// normal case.
func (q *Queries) GetActiveBindingByDevEUI(ctx context.Context, arg GetActiveBindingByDevEUIParams) (GetActiveBindingByDevEUIRow, error) {
	row := q.db.QueryRow(ctx, getActiveBindingByDevEUI, arg.DevEui, arg.ValidFrom)
	var i GetActiveBindingByDevEUIRow
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ReadingOffset,
		&i.LastRawValue,
		&i.DevEui,
		&i.DeviceProfileID,
		&i.CounterModulus,
	)
	return i, err
}

const getActiveBindingByMPID = `-- name: GetActiveBindingByMPID :one
SELECT id, metering_point_id, device_id, valid_from, valid_to, reading_offset, last_raw_value, created_at FROM binding WHERE metering_point_id = $1 AND valid_to IS NULL
`

// MP-side resolver path used by Plan 02-08 MP detail page when caller already
// has the MP id and wants the currently-bound device.
func (q *Queries) GetActiveBindingByMPID(ctx context.Context, meteringPointID pgtype.UUID) (Binding, error) {
	row := q.db.QueryRow(ctx, getActiveBindingByMPID, meteringPointID)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ReadingOffset,
		&i.LastRawValue,
		&i.CreatedAt,
	)
	return i, err
}

const getBinding = `-- name: GetBinding :one
SELECT id, metering_point_id, device_id, valid_from, valid_to, reading_offset, last_raw_value, created_at FROM binding WHERE id = $1
`

func (q *Queries) GetBinding(ctx context.Context, id pgtype.UUID) (Binding, error) {
	row := q.db.QueryRow(ctx, getBinding, id)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ReadingOffset,
		&i.LastRawValue,
		&i.CreatedAt,
	)
	return i, err
}

const listBindingHistoryByDevice = `-- name: ListBindingHistoryByDevice :many
SELECT b.id, b.metering_point_id, b.device_id, b.valid_from, b.valid_to, b.reading_offset, b.last_raw_value, b.created_at, mp.name AS mp_name, mp.site_id FROM binding b
JOIN metering_point mp ON mp.id = b.metering_point_id
WHERE b.device_id = $1
ORDER BY b.valid_from DESC
`

type ListBindingHistoryByDeviceRow struct {
	ID              pgtype.UUID
	MeteringPointID pgtype.UUID
	DeviceID        pgtype.UUID
	ValidFrom       pgtype.Timestamptz
	ValidTo         pgtype.Timestamptz
	ReadingOffset   pgtype.Numeric
	LastRawValue    pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	MpName          string
	SiteID          pgtype.UUID
}

// Plan 02-08 device detail "where has this device been" tab. Symmetric to
// ListBindingHistoryByMP but indexed by device_id.
func (q *Queries) ListBindingHistoryByDevice(ctx context.Context, deviceID pgtype.UUID) ([]ListBindingHistoryByDeviceRow, error) {
	rows, err := q.db.Query(ctx, listBindingHistoryByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBindingHistoryByDeviceRow
	for rows.Next() {
		var i ListBindingHistoryByDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.MeteringPointID,
			&i.DeviceID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ReadingOffset,
			&i.LastRawValue,
			&i.CreatedAt,
			&i.MpName,
			&i.SiteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindingHistoryByMP = `-- name: ListBindingHistoryByMP :many
SELECT b.id, b.metering_point_id, b.device_id, b.valid_from, b.valid_to, b.reading_offset, b.last_raw_value, b.created_at, d.dev_eui, d.name AS device_name FROM binding b
JOIN device d ON d.id = b.device_id
WHERE b.metering_point_id = $1
ORDER BY b.valid_from DESC
`

type ListBindingHistoryByMPRow struct {
	ID              pgtype.UUID
	MeteringPointID pgtype.UUID
	DeviceID        pgtype.UUID
	ValidFrom       pgtype.Timestamptz
	ValidTo         pgtype.Timestamptz
	ReadingOffset   pgtype.Numeric
	LastRawValue    pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	DevEui          string
	DeviceName      string
}

// Plan 02-08 MP detail "binding history" tab. Phase 5 reports also walk this
// by MP_id to attribute historical readings to the right device. Sorted
// newest-first to match the typical "what changed recently" question.
func (q *Queries) ListBindingHistoryByMP(ctx context.Context, meteringPointID pgtype.UUID) ([]ListBindingHistoryByMPRow, error) {
	rows, err := q.db.Query(ctx, listBindingHistoryByMP, meteringPointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBindingHistoryByMPRow
	for rows.Next() {
		var i ListBindingHistoryByMPRow
		if err := rows.Scan(
			&i.ID,
			&i.MeteringPointID,
			&i.DeviceID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ReadingOffset,
			&i.LastRawValue,
			&i.CreatedAt,
			&i.DevEui,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openBinding = `-- name: OpenBinding :one
INSERT INTO binding (metering_point_id, device_id, valid_from, reading_offset)
VALUES ($1, $2, $3, $4)
RETURNING id, metering_point_id, device_id, valid_from, valid_to, reading_offset, last_raw_value, created_at
`

type OpenBindingParams struct {
	MeteringPointID pgtype.UUID
	DeviceID        pgtype.UUID
	ValidFrom       pgtype.Timestamptz
	ReadingOffset   pgtype.Numeric
}

// Plan 02-07 swap commit: opens a new active binding (valid_to = NULL).
// $4 = reading_offset; for a brand-new MP with no prior binding this is 0,
// for a swap the caller computes:
//
//	reading_offset = previous_binding.reading_offset + previous.last_raw_value
//
// so the new binding's "rebase to zero" math (D-05) keeps cumulative_value
// monotonic across the swap.
//
// The btree_gist EXCLUDE constraints (binding_no_overlap_per_mp +
// binding_no_overlap_per_device) make this race-safe — concurrent commits
// on the same MP or same device get 23P01 (exclusion_violation).
func (q *Queries) OpenBinding(ctx context.Context, arg OpenBindingParams) (Binding, error) {
	row := q.db.QueryRow(ctx, openBinding,
		arg.MeteringPointID,
		arg.DeviceID,
		arg.ValidFrom,
		arg.ReadingOffset,
	)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.ReadingOffset,
		&i.LastRawValue,
		&i.CreatedAt,
	)
	return i, err
}

const updateBindingLastRaw = `-- name: UpdateBindingLastRaw :exec
UPDATE binding SET last_raw_value = $2 WHERE id = $1
`

type UpdateBindingLastRawParams struct {
	ID           pgtype.UUID
	LastRawValue pgtype.Numeric
}

// Called by Plan 02-09 ingest after every successful uplink persist.
// Stored on binding (NOT device or measurement) so the rollover detector
// can SELECT one row to fetch the per-binding previous raw counter without
// a JOIN to a 1B-row hypertable (DATA-05 design rationale).
func (q *Queries) UpdateBindingLastRaw(ctx context.Context, arg UpdateBindingLastRawParams) error {
	_, err := q.db.Exec(ctx, updateBindingLastRaw, arg.ID, arg.LastRawValue)
	return err
}
