// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirpstack_connection.sql

package sqlc

import (
	"context"
)

const getChirpStackConnection = `-- name: GetChirpStackConnection :one
SELECT id, mode, grpc_url, api_token_ref, mqtt_url, mqtt_user, mqtt_password_ref, region_name, region_common_name, created_at, updated_at FROM chirpstack_connection WHERE id = 1
`

func (q *Queries) GetChirpStackConnection(ctx context.Context) (ChirpstackConnection, error) {
	row := q.db.QueryRow(ctx, getChirpStackConnection)
	var i ChirpstackConnection
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.GrpcUrl,
		&i.ApiTokenRef,
		&i.MqttUrl,
		&i.MqttUser,
		&i.MqttPasswordRef,
		&i.RegionName,
		&i.RegionCommonName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChirpStackConnection = `-- name: UpsertChirpStackConnection :one
INSERT INTO chirpstack_connection (
    id, mode, grpc_url, api_token_ref,
    mqtt_url, mqtt_user, mqtt_password_ref,
    region_name, region_common_name
)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    mode               = EXCLUDED.mode,
    grpc_url           = EXCLUDED.grpc_url,
    api_token_ref      = EXCLUDED.api_token_ref,
    mqtt_url           = EXCLUDED.mqtt_url,
    mqtt_user          = EXCLUDED.mqtt_user,
    mqtt_password_ref  = EXCLUDED.mqtt_password_ref,
    region_name        = EXCLUDED.region_name,
    region_common_name = EXCLUDED.region_common_name
RETURNING id, mode, grpc_url, api_token_ref, mqtt_url, mqtt_user, mqtt_password_ref, region_name, region_common_name, created_at, updated_at
`

type UpsertChirpStackConnectionParams struct {
	Mode             ChirpstackMode
	GrpcUrl          string
	ApiTokenRef      string
	MqttUrl          string
	MqttUser         *string
	MqttPasswordRef  *string
	RegionName       string
	RegionCommonName string
}

// Plan 15 wizard finish + Phase 5 settings page edit.
func (q *Queries) UpsertChirpStackConnection(ctx context.Context, arg UpsertChirpStackConnectionParams) (ChirpstackConnection, error) {
	row := q.db.QueryRow(ctx, upsertChirpStackConnection,
		arg.Mode,
		arg.GrpcUrl,
		arg.ApiTokenRef,
		arg.MqttUrl,
		arg.MqttUser,
		arg.MqttPasswordRef,
		arg.RegionName,
		arg.RegionCommonName,
	)
	var i ChirpstackConnection
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.GrpcUrl,
		&i.ApiTokenRef,
		&i.MqttUrl,
		&i.MqttUser,
		&i.MqttPasswordRef,
		&i.RegionName,
		&i.RegionCommonName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
