// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirpstack_connection.sql

package sqlc

import (
	"context"
)

const getChirpStackConnection = `-- name: GetChirpStackConnection :one
SELECT id, mode, grpc_url, api_token_ref, mqtt_url, mqtt_user, mqtt_password_ref, region_name, region_common_name, created_at, updated_at, cs_tenant_id, cs_application_id FROM chirpstack_connection WHERE id = 1
`

func (q *Queries) GetChirpStackConnection(ctx context.Context) (ChirpstackConnection, error) {
	row := q.db.QueryRow(ctx, getChirpStackConnection)
	var i ChirpstackConnection
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.GrpcUrl,
		&i.ApiTokenRef,
		&i.MqttUrl,
		&i.MqttUser,
		&i.MqttPasswordRef,
		&i.RegionName,
		&i.RegionCommonName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CsTenantID,
		&i.CsApplicationID,
	)
	return i, err
}

const getChirpStackTenantApp = `-- name: GetChirpStackTenantApp :one
SELECT cs_tenant_id, cs_application_id
FROM chirpstack_connection
WHERE id = 1
`

type GetChirpStackTenantAppRow struct {
	CsTenantID      *string
	CsApplicationID *string
}

// Plan 02-05 boot routine reads the singleton row's CS UUIDs to decide
// whether the bootstrap has already run. NULLs on either column mean the
// bootstrap must execute and back-fill via SetChirpStackTenantApp.
func (q *Queries) GetChirpStackTenantApp(ctx context.Context) (GetChirpStackTenantAppRow, error) {
	row := q.db.QueryRow(ctx, getChirpStackTenantApp)
	var i GetChirpStackTenantAppRow
	err := row.Scan(&i.CsTenantID, &i.CsApplicationID)
	return i, err
}

const setChirpStackTenantApp = `-- name: SetChirpStackTenantApp :exec
UPDATE chirpstack_connection
SET cs_tenant_id = $1, cs_application_id = $2
WHERE id = 1
`

type SetChirpStackTenantAppParams struct {
	CsTenantID      *string
	CsApplicationID *string
}

// Plan 02-05 first-boot bootstrap (EnsureTenantAndApplication, D-28) —
// persists the ChirpStack-side UUIDs after the tenant + application are
// created or reused. Subsequent boots read GetChirpStackTenantApp and skip
// the gRPC calls entirely; idempotent restart is a no-op.
func (q *Queries) SetChirpStackTenantApp(ctx context.Context, arg SetChirpStackTenantAppParams) error {
	_, err := q.db.Exec(ctx, setChirpStackTenantApp, arg.CsTenantID, arg.CsApplicationID)
	return err
}

const upsertChirpStackConnection = `-- name: UpsertChirpStackConnection :one
INSERT INTO chirpstack_connection (
    id, mode, grpc_url, api_token_ref,
    mqtt_url, mqtt_user, mqtt_password_ref,
    region_name, region_common_name
)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    mode               = EXCLUDED.mode,
    grpc_url           = EXCLUDED.grpc_url,
    api_token_ref      = EXCLUDED.api_token_ref,
    mqtt_url           = EXCLUDED.mqtt_url,
    mqtt_user          = EXCLUDED.mqtt_user,
    mqtt_password_ref  = EXCLUDED.mqtt_password_ref,
    region_name        = EXCLUDED.region_name,
    region_common_name = EXCLUDED.region_common_name
RETURNING id, mode, grpc_url, api_token_ref, mqtt_url, mqtt_user, mqtt_password_ref, region_name, region_common_name, created_at, updated_at, cs_tenant_id, cs_application_id
`

type UpsertChirpStackConnectionParams struct {
	Mode             ChirpstackMode
	GrpcUrl          string
	ApiTokenRef      string
	MqttUrl          string
	MqttUser         *string
	MqttPasswordRef  *string
	RegionName       string
	RegionCommonName string
}

// Plan 15 wizard finish + Phase 5 settings page edit.
func (q *Queries) UpsertChirpStackConnection(ctx context.Context, arg UpsertChirpStackConnectionParams) (ChirpstackConnection, error) {
	row := q.db.QueryRow(ctx, upsertChirpStackConnection,
		arg.Mode,
		arg.GrpcUrl,
		arg.ApiTokenRef,
		arg.MqttUrl,
		arg.MqttUser,
		arg.MqttPasswordRef,
		arg.RegionName,
		arg.RegionCommonName,
	)
	var i ChirpstackConnection
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.GrpcUrl,
		&i.ApiTokenRef,
		&i.MqttUrl,
		&i.MqttUser,
		&i.MqttPasswordRef,
		&i.RegionName,
		&i.RegionCommonName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CsTenantID,
		&i.CsApplicationID,
	)
	return i, err
}
