// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareMeteringPointDaily = `-- name: CompareMeteringPointDaily :many
SELECT
  bucket::date                                   AS bucket,
  round(coalesce(cumulative_delta, 0))::bigint   AS value
FROM measurement_daily
WHERE metering_point_id = $1
  AND bucket >= $2
  AND bucket <  $3
ORDER BY bucket::date
`

type CompareMeteringPointDailyParams struct {
	MeteringPointID pgtype.UUID
	Bucket          interface{}
	Bucket_2        interface{}
}

type CompareMeteringPointDailyRow struct {
	Bucket pgtype.Date
	Value  int64
}

// Returns daily consumption totals for a single metering point.
func (q *Queries) CompareMeteringPointDaily(ctx context.Context, arg CompareMeteringPointDailyParams) ([]CompareMeteringPointDailyRow, error) {
	rows, err := q.db.Query(ctx, compareMeteringPointDaily, arg.MeteringPointID, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareMeteringPointDailyRow
	for rows.Next() {
		var i CompareMeteringPointDailyRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compareSiteDaily = `-- name: CompareSiteDaily :many

SELECT
  md.bucket::date          AS bucket,
  round(coalesce(sum(md.cumulative_delta), 0))::bigint AS value
FROM measurement_daily md
JOIN metering_point mp ON mp.id = md.metering_point_id
WHERE mp.site_id = $1
  AND md.bucket >= $2
  AND md.bucket <  $3
GROUP BY md.bucket::date
ORDER BY md.bucket::date
`

type CompareSiteDailyParams struct {
	SiteID   pgtype.UUID
	Bucket   interface{}
	Bucket_2 interface{}
}

type CompareSiteDailyRow struct {
	Bucket pgtype.Date
	Value  int64
}

// compare.sql
// sqlc-annotated queries for the Plan 07-12 Compare View (Surface 5).
// Both queries hit measurement_daily CAGG for day-level bucketing.
// Range param semantics: from inclusive, to exclusive (half-open interval).
// Returns daily consumption totals for a given site (summing all metering points).
// value cast to bigint (rounded m³) so sqlc maps it to int64 cleanly.
func (q *Queries) CompareSiteDaily(ctx context.Context, arg CompareSiteDailyParams) ([]CompareSiteDailyRow, error) {
	rows, err := q.db.Query(ctx, compareSiteDaily, arg.SiteID, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareSiteDailyRow
	for rows.Next() {
		var i CompareSiteDailyRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
