// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one

INSERT INTO device (dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at
`

type CreateDeviceParams struct {
	DevEui          string
	Name            string
	DeviceProfileID pgtype.UUID
	CsDeviceUuid    *string
	JoinEui         *string
	Description     *string
}

// Device — physical LoRaWAN endpoint (D-15 + D-25 + DEV-09). dev_eui is the
// LoRaWAN-canonical 16-char lowercase hex string (CS uses lowercase across
// v4 gRPC + MQTT topics — Plan 01-12). Schema CHECK enforces both the
// lowercase + hex16 invariants.
// Plan 02-08 device dialog. cs_device_uuid filled by Plan 02-05 wrapper after
// the ChirpStack DeviceService.Create gRPC ack. join_eui optional; AppKey is
// DELIBERATELY NOT stored here (DEV-09 — secret lives in ChirpStack only).
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.DevEui,
		arg.Name,
		arg.DeviceProfileID,
		arg.CsDeviceUuid,
		arg.JoinEui,
		arg.Description,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decommissionDevice = `-- name: DecommissionDevice :one
UPDATE device SET decommissioned_at = now()
WHERE id = $1 AND decommissioned_at IS NULL
RETURNING id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at
`

// D-15 decommission: marks the device retired. The active binding closure
// is a separate transaction (Plan 02-07 swap.commit calls CloseBinding)
// because the binding may already be closed when the operator decommissions
// (or vice versa); the application layer composes them.
func (q *Queries) DecommissionDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, decommissionDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at FROM device WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByDevEUI = `-- name: GetDeviceByDevEUI :one
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at FROM device WHERE dev_eui = $1
`

// Used by Plan 02-07 swap commit to find the incoming device by EUI before
// opening the new binding. Caller MUST pass lower-cased EUI; the schema CHECK
// guards but the unique-index hit needs the lowercase form.
func (q *Queries) GetDeviceByDevEUI(ctx context.Context, devEui string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByDevEUI, devEui)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDevices = `-- name: ListActiveDevices :many
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at FROM device
WHERE decommissioned_at IS NULL
ORDER BY last_seen_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListActiveDevicesParams struct {
	Limit  int32
	Offset int32
}

// Devices list page (Plan 02-08 device list). Sorted last_seen_at DESC NULLS
// LAST so freshly-uplinking devices float to the top; LIMIT/OFFSET for the
// paginated list. Phase 2 minimal — device counts under 100 for v1 installs.
func (q *Queries) ListActiveDevices(ctx context.Context, arg ListActiveDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listActiveDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySite = `-- name: ListDevicesBySite :many
SELECT d.id, d.dev_eui, d.name, d.device_profile_id, d.cs_device_uuid, d.join_eui, d.description, d.last_seen_at, d.decommissioned_at, d.created_at, d.updated_at FROM device d
JOIN binding b ON b.device_id = d.id AND b.valid_to IS NULL
JOIN metering_point mp ON mp.id = b.metering_point_id
WHERE mp.site_id = $1 AND d.decommissioned_at IS NULL
ORDER BY d.last_seen_at DESC NULLS LAST
`

// Site detail page section: devices currently bound to MPs on this site.
// The JOIN through binding (active only) → metering_point handles the
// "device → site" association which is otherwise indirect (devices have no
// direct site_id; that's by design — D-15 + DATA-01).
func (q *Queries) ListDevicesBySite(ctx context.Context, siteID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDevices = `-- name: SearchDevices :many
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at FROM device
WHERE decommissioned_at IS NULL
  AND (name ILIKE '%' || $1 || '%' OR dev_eui ILIKE '%' || lower($1) || '%')
ORDER BY last_seen_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type SearchDevicesParams struct {
	Column1 *string
	Limit   int32
	Offset  int32
}

// Devices list page search (Phase 2 minimal: name OR dev_eui). The dev_eui
// ILIKE branch lower()s the input so the user can paste an EUI in any case
// and still hit the schema's lowercase-only column. T-02-06-03: this is
// unindexed by design for Phase 2's sub-100-device installs; Phase 3 DEV-01
// will add proper FTS or trigram index when device counts cross ~1K.
func (q *Queries) SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, searchDevices, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceCSUUID = `-- name: SetDeviceCSUUID :exec
UPDATE device SET cs_device_uuid = $2 WHERE id = $1
`

type SetDeviceCSUUIDParams struct {
	ID           pgtype.UUID
	CsDeviceUuid *string
}

// Called by Plan 02-05 atomic-create-rollback path after ChirpStack confirms
// the device — fills the cs_device_uuid column so subsequent gRPC calls can
// address by UUID rather than dev_eui.
func (q *Queries) SetDeviceCSUUID(ctx context.Context, arg SetDeviceCSUUIDParams) error {
	_, err := q.db.Exec(ctx, setDeviceCSUUID, arg.ID, arg.CsDeviceUuid)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE device SET
    name = $2, join_eui = $3, description = $4
WHERE id = $1
RETURNING id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID          pgtype.UUID
	Name        string
	JoinEui     *string
	Description *string
}

// Plan 02-08 device edit dialog. dev_eui + device_profile_id are
// intentionally NOT updatable here — changing either is a "swap" workflow
// (close the binding, decommission/recreate device) per D-15.
func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.JoinEui,
		arg.Description,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE device SET last_seen_at = $2 WHERE id = $1
`

type UpdateDeviceLastSeenParams struct {
	ID         pgtype.UUID
	LastSeenAt pgtype.Timestamptz
}

// Called by ingest pipeline (Plan 02-09) on every successful uplink. The
// per-device write rate is bounded (one row per uplink ≤ once per minute
// for the highest-frequency Phase 2 vendor); no need to batch.
func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, arg.ID, arg.LastSeenAt)
	return err
}
