// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevicesFiltered = `-- name: CountDevicesFiltered :one
WITH active_bindings AS (
    SELECT b.device_id, mp.site_id
    FROM binding b
    JOIN metering_point mp ON mp.id = b.metering_point_id
    WHERE b.valid_to IS NULL
)
SELECT COUNT(*)
FROM device d
LEFT JOIN active_bindings ab ON ab.device_id = d.id
WHERE d.decommissioned_at IS NULL
  AND (cardinality($1::uuid[]) = 0 OR ab.site_id = ANY($1::uuid[]))
  AND (
        $2::text = ''
        OR ($2 = 'active'        AND d.last_seen_at IS NOT NULL AND d.last_seen_at >  now() - interval '24 hours')
        OR ($2 = 'inactive'      AND d.last_seen_at IS NOT NULL AND d.last_seen_at <= now() - interval '24 hours')
        OR ($2 = 'never_joined'  AND d.last_seen_at IS NULL)
      )
  AND ($3::timestamptz IS NULL OR d.last_seen_at >= $3)
  AND (
        $4::text = ''
        OR d.name    ILIKE '%' || $4 || '%'
        OR d.dev_eui ILIKE '%' || $4 || '%'
      )
`

type CountDevicesFilteredParams struct {
	Column1 []pgtype.UUID
	Column2 string
	Column3 pgtype.Timestamptz
	Column4 string
}

// Same WHERE clause as ListDevicesFiltered for accurate total_count.
func (q *Queries) CountDevicesFiltered(ctx context.Context, arg CountDevicesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO device (dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id
`

type CreateDeviceParams struct {
	DevEui          string
	Name            string
	DeviceProfileID pgtype.UUID
	CsDeviceUuid    *string
	JoinEui         *string
	Description     *string
}

// Device — physical LoRaWAN endpoint (D-15 + D-25 + DEV-09). dev_eui is the
// LoRaWAN-canonical 16-char lowercase hex string (CS uses lowercase across
// v4 gRPC + MQTT topics — Plan 01-12). Schema CHECK enforces both the
// lowercase + hex16 invariants.
// Plan 02-08 device dialog. cs_device_uuid filled by Plan 02-05 wrapper after
// the ChirpStack DeviceService.Create gRPC ack. join_eui optional; AppKey is
// DELIBERATELY NOT stored here (DEV-09 — secret lives in ChirpStack only).
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.DevEui,
		arg.Name,
		arg.DeviceProfileID,
		arg.CsDeviceUuid,
		arg.JoinEui,
		arg.Description,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayID,
	)
	return i, err
}

const decommissionDevice = `-- name: DecommissionDevice :one
UPDATE device SET decommissioned_at = now()
WHERE id = $1 AND decommissioned_at IS NULL
RETURNING id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id
`

// D-15 decommission: marks the device retired. The active binding closure
// is a separate transaction (Plan 02-07 swap.commit calls CloseBinding)
// because the binding may already be closed when the operator decommissions
// (or vice versa); the application layer composes them.
func (q *Queries) DecommissionDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, decommissionDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayID,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id FROM device WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayID,
	)
	return i, err
}

const getDeviceByDevEUI = `-- name: GetDeviceByDevEUI :one
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id FROM device WHERE dev_eui = $1
`

// Used by Plan 02-07 swap commit to find the incoming device by EUI before
// opening the new binding. Caller MUST pass lower-cased EUI; the schema CHECK
// guards but the unique-index hit needs the lowercase form.
func (q *Queries) GetDeviceByDevEUI(ctx context.Context, devEui string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByDevEUI, devEui)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayID,
	)
	return i, err
}

const listActiveDevices = `-- name: ListActiveDevices :many
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id FROM device
WHERE decommissioned_at IS NULL
ORDER BY last_seen_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListActiveDevicesParams struct {
	Limit  int32
	Offset int32
}

// Devices list page (Plan 02-08 device list). Sorted last_seen_at DESC NULLS
// LAST so freshly-uplinking devices float to the top; LIMIT/OFFSET for the
// paginated list. Phase 2 minimal — device counts under 100 for v1 installs.
func (q *Queries) ListActiveDevices(ctx context.Context, arg ListActiveDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listActiveDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GatewayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySite = `-- name: ListDevicesBySite :many
SELECT d.id, d.dev_eui, d.name, d.device_profile_id, d.cs_device_uuid, d.join_eui, d.description, d.last_seen_at, d.decommissioned_at, d.created_at, d.updated_at, d.gateway_id FROM device d
JOIN binding b ON b.device_id = d.id AND b.valid_to IS NULL
JOIN metering_point mp ON mp.id = b.metering_point_id
WHERE mp.site_id = $1 AND d.decommissioned_at IS NULL
ORDER BY d.last_seen_at DESC NULLS LAST
`

// Site detail page section: devices currently bound to MPs on this site.
// The JOIN through binding (active only) → metering_point handles the
// "device → site" association which is otherwise indirect (devices have no
// direct site_id; that's by design — D-15 + DATA-01).
func (q *Queries) ListDevicesBySite(ctx context.Context, siteID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GatewayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesFiltered = `-- name: ListDevicesFiltered :many
WITH active_bindings AS (
    SELECT b.device_id, mp.site_id, s.name AS site_name
    FROM binding b
    JOIN metering_point mp ON mp.id = b.metering_point_id
    JOIN site s ON s.id = mp.site_id
    WHERE b.valid_to IS NULL
)
SELECT
    d.id,
    d.dev_eui,
    d.name,
    d.device_profile_id,
    d.cs_device_uuid,
    d.join_eui,
    d.description,
    d.last_seen_at,
    d.decommissioned_at,
    d.created_at,
    d.updated_at,
    ab.site_id   AS current_site_id,
    ab.site_name AS current_site_name
FROM device d
LEFT JOIN active_bindings ab ON ab.device_id = d.id
WHERE d.decommissioned_at IS NULL
  AND (
        cardinality($1::uuid[]) = 0
        OR ab.site_id = ANY($1::uuid[])
      )
  AND (
        $2::text = ''
        OR ($2 = 'active'        AND d.last_seen_at IS NOT NULL AND d.last_seen_at >  now() - interval '24 hours')
        OR ($2 = 'inactive'      AND d.last_seen_at IS NOT NULL AND d.last_seen_at <= now() - interval '24 hours')
        OR ($2 = 'never_joined'  AND d.last_seen_at IS NULL)
      )
  AND ($3::timestamptz IS NULL OR d.last_seen_at >= $3)
  AND (
        $4::text = ''
        OR d.name    ILIKE '%' || $4 || '%'
        OR d.dev_eui ILIKE '%' || $4 || '%'
      )
ORDER BY
    CASE WHEN $5::text = 'name'        AND $6::bool = false THEN d.name             END ASC,
    CASE WHEN $5::text = 'name'        AND $6::bool = true  THEN d.name             END DESC,
    CASE WHEN $5::text = 'dev_eui'     AND $6::bool = false THEN d.dev_eui          END ASC,
    CASE WHEN $5::text = 'dev_eui'     AND $6::bool = true  THEN d.dev_eui          END DESC,
    CASE WHEN $5::text = 'site'        AND $6::bool = false THEN ab.site_name       END ASC NULLS LAST,
    CASE WHEN $5::text = 'site'        AND $6::bool = true  THEN ab.site_name       END DESC NULLS LAST,
    CASE WHEN $5::text = 'last_seen'   AND $6::bool = false THEN d.last_seen_at     END ASC NULLS LAST,
    CASE WHEN $5::text = 'last_seen'   AND $6::bool = true  THEN d.last_seen_at     END DESC NULLS LAST,
    CASE WHEN $5::text = 'created_at'  AND $6::bool = false THEN d.created_at       END ASC,
    CASE WHEN $5::text = 'created_at'  AND $6::bool = true  THEN d.created_at       END DESC,
    d.last_seen_at DESC NULLS LAST,
    d.id ASC
LIMIT $7 OFFSET $8
`

type ListDevicesFilteredParams struct {
	Column1 []pgtype.UUID
	Column2 string
	Column3 pgtype.Timestamptz
	Column4 string
	Column5 string
	Column6 bool
	Limit   int32
	Offset  int32
}

type ListDevicesFilteredRow struct {
	ID               pgtype.UUID
	DevEui           string
	Name             string
	DeviceProfileID  pgtype.UUID
	CsDeviceUuid     *string
	JoinEui          *string
	Description      *string
	LastSeenAt       pgtype.Timestamptz
	DecommissionedAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CurrentSiteID    pgtype.UUID
	CurrentSiteName  *string
}

// Phase 3 D-12..D-18: server-side filter/sort/page for the Devices list.
// Site join via active binding (no current_site_id denormalisation per
// RESEARCH Open Q #2). The device schema's soft-delete column is
// decommissioned_at (see migration 0012), not archived_at — the plan-level
// "archived_at" wording refers to "live" devices and maps to
// `decommissioned_at IS NULL` here.
// Filter args:
//
//	$1 = site_ids UUID[] — empty = no filter
//	$2 = status_filter TEXT — 'active'|'inactive'|'never_joined'|'' (empty = no filter)
//	$3 = last_seen_cutoff TIMESTAMPTZ NULL — devices with last_seen_at >= cutoff (or any if NULL)
//	$4 = text_q TEXT — '' = no filter; matches name ILIKE %q% OR dev_eui ILIKE %q%
//	$5 = sort_col TEXT — 'name'|'dev_eui'|'site'|'last_seen'|'created_at'
//	$6 = sort_desc BOOL
//	$7 = limit_n INT
//	$8 = offset_n INT
func (q *Queries) ListDevicesFiltered(ctx context.Context, arg ListDevicesFilteredParams) ([]ListDevicesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listDevicesFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesFilteredRow
	for rows.Next() {
		var i ListDevicesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentSiteID,
			&i.CurrentSiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDevices = `-- name: SearchDevices :many
SELECT id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id FROM device
WHERE decommissioned_at IS NULL
  AND (name ILIKE '%' || $1 || '%' OR dev_eui ILIKE '%' || lower($1) || '%')
ORDER BY last_seen_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type SearchDevicesParams struct {
	Column1 *string
	Limit   int32
	Offset  int32
}

// Devices list page search (Phase 2 minimal: name OR dev_eui). The dev_eui
// ILIKE branch lower()s the input so the user can paste an EUI in any case
// and still hit the schema's lowercase-only column. T-02-06-03: this is
// unindexed by design for Phase 2's sub-100-device installs; Phase 3 DEV-01
// will add proper FTS or trigram index when device counts cross ~1K.
func (q *Queries) SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, searchDevices, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DevEui,
			&i.Name,
			&i.DeviceProfileID,
			&i.CsDeviceUuid,
			&i.JoinEui,
			&i.Description,
			&i.LastSeenAt,
			&i.DecommissionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GatewayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceCSUUID = `-- name: SetDeviceCSUUID :exec
UPDATE device SET cs_device_uuid = $2 WHERE id = $1
`

type SetDeviceCSUUIDParams struct {
	ID           pgtype.UUID
	CsDeviceUuid *string
}

// Called by Plan 02-05 atomic-create-rollback path after ChirpStack confirms
// the device — fills the cs_device_uuid column so subsequent gRPC calls can
// address by UUID rather than dev_eui.
func (q *Queries) SetDeviceCSUUID(ctx context.Context, arg SetDeviceCSUUIDParams) error {
	_, err := q.db.Exec(ctx, setDeviceCSUUID, arg.ID, arg.CsDeviceUuid)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE device SET
    name = $2, join_eui = $3, description = $4
WHERE id = $1
RETURNING id, dev_eui, name, device_profile_id, cs_device_uuid, join_eui, description, last_seen_at, decommissioned_at, created_at, updated_at, gateway_id
`

type UpdateDeviceParams struct {
	ID          pgtype.UUID
	Name        string
	JoinEui     *string
	Description *string
}

// Plan 02-08 device edit dialog. dev_eui + device_profile_id are
// intentionally NOT updatable here — changing either is a "swap" workflow
// (close the binding, decommission/recreate device) per D-15.
func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.JoinEui,
		arg.Description,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DevEui,
		&i.Name,
		&i.DeviceProfileID,
		&i.CsDeviceUuid,
		&i.JoinEui,
		&i.Description,
		&i.LastSeenAt,
		&i.DecommissionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayID,
	)
	return i, err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE device SET last_seen_at = $2 WHERE id = $1
`

type UpdateDeviceLastSeenParams struct {
	ID         pgtype.UUID
	LastSeenAt pgtype.Timestamptz
}

// Called by ingest pipeline (Plan 02-09) on every successful uplink. The
// per-device write rate is bounded (one row per uplink ≤ once per minute
// for the highest-frequency Phase 2 vendor); no need to batch.
func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, arg.ID, arg.LastSeenAt)
	return err
}
