// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_profile_mappings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMappingsByProfile = `-- name: CountMappingsByProfile :one
SELECT count(*) FROM device_profile_mapping WHERE device_profile_id = $1
`

// Profile list page badge "N mappings" — quick count without fetching rows.
func (q *Queries) CountMappingsByProfile(ctx context.Context, deviceProfileID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMappingsByProfile, deviceProfileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMapping = `-- name: CreateMapping :one

INSERT INTO device_profile_mapping (
    device_profile_id, json_pointer, target, scale, data_type, position
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_profile_id, json_pointer, target, scale, data_type, position, created_at, updated_at
`

type CreateMappingParams struct {
	DeviceProfileID pgtype.UUID
	JsonPointer     string
	Target          string
	Scale           pgtype.Numeric
	DataType        string
	Position        int32
}

// Device Profile Mapping (D-08 + DATA-09) — rows from decoded JSON to
// canonical measurement columns. The Plan 02-08 profile editor saves the
// whole mapping list at once: DeleteMappingsByProfile then a sequence of
// CreateMapping calls inside a single transaction (replace-all semantics
// so the editor never leaves a half-saved mapping set).
// Plan 02-08 profile editor save (per-row insert). UNIQUE (device_profile_id,
// target) surfaces as 23505 if the editor lets two rows claim the same
// canonical column — handler maps to a friendly error.
func (q *Queries) CreateMapping(ctx context.Context, arg CreateMappingParams) (DeviceProfileMapping, error) {
	row := q.db.QueryRow(ctx, createMapping,
		arg.DeviceProfileID,
		arg.JsonPointer,
		arg.Target,
		arg.Scale,
		arg.DataType,
		arg.Position,
	)
	var i DeviceProfileMapping
	err := row.Scan(
		&i.ID,
		&i.DeviceProfileID,
		&i.JsonPointer,
		&i.Target,
		&i.Scale,
		&i.DataType,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMapping = `-- name: DeleteMapping :exec
DELETE FROM device_profile_mapping WHERE id = $1
`

// Single-row delete — used by Phase 6 admin actions; Phase 2's editor uses
// the bulk DeleteMappingsByProfile path.
func (q *Queries) DeleteMapping(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMapping, id)
	return err
}

const deleteMappingsByProfile = `-- name: DeleteMappingsByProfile :exec
DELETE FROM device_profile_mapping WHERE device_profile_id = $1
`

// Plan 02-08 profile editor save: wipes existing mappings before bulk
// re-insert. Wrapped in a tx with the subsequent CreateMapping calls so
// the editor never observes a half-saved state.
func (q *Queries) DeleteMappingsByProfile(ctx context.Context, deviceProfileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMappingsByProfile, deviceProfileID)
	return err
}

const getMapping = `-- name: GetMapping :one
SELECT id, device_profile_id, json_pointer, target, scale, data_type, position, created_at, updated_at FROM device_profile_mapping WHERE id = $1
`

func (q *Queries) GetMapping(ctx context.Context, id pgtype.UUID) (DeviceProfileMapping, error) {
	row := q.db.QueryRow(ctx, getMapping, id)
	var i DeviceProfileMapping
	err := row.Scan(
		&i.ID,
		&i.DeviceProfileID,
		&i.JsonPointer,
		&i.Target,
		&i.Scale,
		&i.DataType,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMappingsByProfile = `-- name: ListMappingsByProfile :many
SELECT id, device_profile_id, json_pointer, target, scale, data_type, position, created_at, updated_at FROM device_profile_mapping
WHERE device_profile_id = $1
ORDER BY position ASC, target ASC
`

// Plan 02-09 normalize engine: fetches the mapping table once at boot and
// caches per-profile (cache invalidates on profile save). Position ASC drives
// deterministic mapping pass order — required when a later mapping references
// a value materialized by an earlier one.
func (q *Queries) ListMappingsByProfile(ctx context.Context, deviceProfileID pgtype.UUID) ([]DeviceProfileMapping, error) {
	rows, err := q.db.Query(ctx, listMappingsByProfile, deviceProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceProfileMapping
	for rows.Next() {
		var i DeviceProfileMapping
		if err := rows.Scan(
			&i.ID,
			&i.DeviceProfileID,
			&i.JsonPointer,
			&i.Target,
			&i.Scale,
			&i.DataType,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
