// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveDeviceProfile = `-- name: ArchiveDeviceProfile :one
UPDATE device_profile SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at
`

// D-20 soft-delete for profiles. Note: device.device_profile_id has
// ON DELETE RESTRICT, so the row stays referenceable even when archived
// (existing devices keep working; archive only hides from the create-device
// dropdown).
func (q *Queries) ArchiveDeviceProfile(ctx context.Context, id pgtype.UUID) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, archiveDeviceProfile, id)
	var i DeviceProfile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Vendor,
		&i.Family,
		&i.Capabilities,
		&i.CounterModulus,
		&i.CodecJs,
		&i.CsProfileID,
		&i.CodecJsSyncedAt,
		&i.Region,
		&i.MacVersion,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeviceProfile = `-- name: CreateDeviceProfile :one

INSERT INTO device_profile (
    slug, name, vendor, family, capabilities, counter_modulus,
    codec_js, region, mac_version
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at
`

type CreateDeviceProfileParams struct {
	Slug           string
	Name           string
	Vendor         string
	Family         *string
	Capabilities   []string
	CounterModulus int64
	CodecJs        string
	Region         *string
	MacVersion     string
}

// Device Profile (D-01 layer 2 + D-04 capabilities + D-05 counter_modulus +
// D-09 codec sync state). Seeded by 0010 with three vendor profiles
// (axioma_w1, acrel_adl200, acrel_adw300); the bootstrap routine in
// internal/profile/seed.go (Plan 02-08) reads //go:embed-ed *.js codec
// bodies, pushes them to ChirpStack, and back-fills cs_profile_id +
// codec_js_synced_at via MarkProfileSyncedToChirpStack.
// Plan 02-08 profile editor "create new profile" path (rare in practice;
// seeded profiles cover Phase 2 — operator-authored profiles unlock in
// Phase 6). codec_js may be empty at creation; the seed routine fills it.
func (q *Queries) CreateDeviceProfile(ctx context.Context, arg CreateDeviceProfileParams) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, createDeviceProfile,
		arg.Slug,
		arg.Name,
		arg.Vendor,
		arg.Family,
		arg.Capabilities,
		arg.CounterModulus,
		arg.CodecJs,
		arg.Region,
		arg.MacVersion,
	)
	var i DeviceProfile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Vendor,
		&i.Family,
		&i.Capabilities,
		&i.CounterModulus,
		&i.CodecJs,
		&i.CsProfileID,
		&i.CodecJsSyncedAt,
		&i.Region,
		&i.MacVersion,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceProfile = `-- name: GetDeviceProfile :one
SELECT id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at FROM device_profile WHERE id = $1
`

func (q *Queries) GetDeviceProfile(ctx context.Context, id pgtype.UUID) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, getDeviceProfile, id)
	var i DeviceProfile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Vendor,
		&i.Family,
		&i.Capabilities,
		&i.CounterModulus,
		&i.CodecJs,
		&i.CsProfileID,
		&i.CodecJsSyncedAt,
		&i.Region,
		&i.MacVersion,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceProfileBySlug = `-- name: GetDeviceProfileBySlug :one
SELECT id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at FROM device_profile WHERE slug = $1
`

// Plan 02-08 seed routine + Plan 02-08 profile editor URL routing
// (`/profiles/axioma_w1`).
func (q *Queries) GetDeviceProfileBySlug(ctx context.Context, slug string) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, getDeviceProfileBySlug, slug)
	var i DeviceProfile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Vendor,
		&i.Family,
		&i.Capabilities,
		&i.CounterModulus,
		&i.CodecJs,
		&i.CsProfileID,
		&i.CodecJsSyncedAt,
		&i.Region,
		&i.MacVersion,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDeviceProfiles = `-- name: ListActiveDeviceProfiles :many
SELECT id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at FROM device_profile
WHERE archived_at IS NULL
ORDER BY vendor ASC, name ASC
`

// Profile list page + device-create dialog dropdown. Sorted vendor-then-name
// so users see Acrel/Axioma grouped.
func (q *Queries) ListActiveDeviceProfiles(ctx context.Context) ([]DeviceProfile, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceProfile
	for rows.Next() {
		var i DeviceProfile
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Vendor,
			&i.Family,
			&i.Capabilities,
			&i.CounterModulus,
			&i.CodecJs,
			&i.CsProfileID,
			&i.CodecJsSyncedAt,
			&i.Region,
			&i.MacVersion,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsyncedProfiles = `-- name: ListUnsyncedProfiles :many
SELECT id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at FROM device_profile
WHERE archived_at IS NULL
  AND (cs_profile_id IS NULL OR codec_js_synced_at IS NULL)
`

// Plan 02-08 boot-time seed routine reads this list to decide which profiles
// need a CS push. A profile is "unsynced" if it has no cs_profile_id (never
// pushed) OR the codec_js was modified after the last push (codec_js_synced_at
// is NULL after a SetProfileCodecJS write — the seed routine sets it back
// to now() once CS confirms the new codec).
func (q *Queries) ListUnsyncedProfiles(ctx context.Context) ([]DeviceProfile, error) {
	rows, err := q.db.Query(ctx, listUnsyncedProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceProfile
	for rows.Next() {
		var i DeviceProfile
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Vendor,
			&i.Family,
			&i.Capabilities,
			&i.CounterModulus,
			&i.CodecJs,
			&i.CsProfileID,
			&i.CodecJsSyncedAt,
			&i.Region,
			&i.MacVersion,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProfileSyncedToChirpStack = `-- name: MarkProfileSyncedToChirpStack :exec
UPDATE device_profile
SET cs_profile_id = $2, codec_js_synced_at = now()
WHERE id = $1
`

type MarkProfileSyncedToChirpStackParams struct {
	ID          pgtype.UUID
	CsProfileID pgtype.UUID
}

// Plan 02-08 seed routine — called after a successful CS DeviceProfileService
// Create/Update gRPC call. Records the CS-side UUID + sync timestamp so the
// next boot's ListUnsyncedProfiles query no longer returns this row.
func (q *Queries) MarkProfileSyncedToChirpStack(ctx context.Context, arg MarkProfileSyncedToChirpStackParams) error {
	_, err := q.db.Exec(ctx, markProfileSyncedToChirpStack, arg.ID, arg.CsProfileID)
	return err
}

const setProfileCodecJS = `-- name: SetProfileCodecJS :exec
UPDATE device_profile
SET codec_js = $2, codec_js_synced_at = NULL
WHERE id = $1
`

type SetProfileCodecJSParams struct {
	ID      pgtype.UUID
	CodecJs string
}

// Plan 02-08 seed routine — writes the //go:embed-ed codec body into the row
// and clears codec_js_synced_at so the next pass re-pushes to ChirpStack.
func (q *Queries) SetProfileCodecJS(ctx context.Context, arg SetProfileCodecJSParams) error {
	_, err := q.db.Exec(ctx, setProfileCodecJS, arg.ID, arg.CodecJs)
	return err
}

const updateDeviceProfile = `-- name: UpdateDeviceProfile :one
UPDATE device_profile SET
    name = $2, vendor = $3, family = $4,
    capabilities = $5, counter_modulus = $6,
    codec_js = $7, region = $8, mac_version = $9
WHERE id = $1
RETURNING id, slug, name, vendor, family, capabilities, counter_modulus, codec_js, cs_profile_id, codec_js_synced_at, region, mac_version, archived_at, created_at, updated_at
`

type UpdateDeviceProfileParams struct {
	ID             pgtype.UUID
	Name           string
	Vendor         string
	Family         *string
	Capabilities   []string
	CounterModulus int64
	CodecJs        string
	Region         *string
	MacVersion     string
}

// Plan 02-08 profile editor save path. capabilities + counter_modulus + codec
// are all editable; mappings are stored in device_profile_mapping (separate
// queries — see device_profile_mappings.sql). cs_profile_id is intentionally
// NOT updatable here; only MarkProfileSyncedToChirpStack writes that column.
func (q *Queries) UpdateDeviceProfile(ctx context.Context, arg UpdateDeviceProfileParams) (DeviceProfile, error) {
	row := q.db.QueryRow(ctx, updateDeviceProfile,
		arg.ID,
		arg.Name,
		arg.Vendor,
		arg.Family,
		arg.Capabilities,
		arg.CounterModulus,
		arg.CodecJs,
		arg.Region,
		arg.MacVersion,
	)
	var i DeviceProfile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Vendor,
		&i.Family,
		&i.Capabilities,
		&i.CounterModulus,
		&i.CodecJs,
		&i.CsProfileID,
		&i.CodecJsSyncedAt,
		&i.Region,
		&i.MacVersion,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
