// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: floor_plan.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPinsOnFloorPlan = `-- name: CountPinsOnFloorPlan :one
SELECT count(*) FROM device_floor_plan_placement WHERE floor_plan_id = $1
`

// Used by the PATCH replace-image handler to build the D-24 confirmation
// dialog copy: "Existing {N} pins will be kept at the same fractional
// positions on the new image."
func (q *Queries) CountPinsOnFloorPlan(ctx context.Context, floorPlanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPinsOnFloorPlan, floorPlanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFloorPlan = `-- name: CreateFloorPlan :one

INSERT INTO floor_plan (id, site_id, label, sort_order, image_path, image_w, image_h)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, site_id, label, sort_order, image_path, image_w, image_h, uploaded_at, updated_at
`

type CreateFloorPlanParams struct {
	ID        pgtype.UUID
	SiteID    pgtype.UUID
	Label     string
	SortOrder int32
	ImagePath string
	ImageW    int32
	ImageH    int32
}

// floor_plan.sql — Phase 5 SITE-02/03 (D-16 schema + D-18 image storage).
// Serves upload (CreateFloorPlan), listing (ListFloorPlansBySite), detail
// (GetFloorPlan), image replace (UpdateFloorPlanImage), rename (UpdateFloorPlanLabel),
// delete (DeleteFloorPlan), and pin-count (CountPinsOnFloorPlan).
// Upload handler inserts immediately after the image bytes are written to
// disk (before tx commit). sort_order defaults to the next slot; UNIQUE
// (site_id, sort_order) rejects duplicates with a 23505 error.
func (q *Queries) CreateFloorPlan(ctx context.Context, arg CreateFloorPlanParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, createFloorPlan,
		arg.ID,
		arg.SiteID,
		arg.Label,
		arg.SortOrder,
		arg.ImagePath,
		arg.ImageW,
		arg.ImageH,
	)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Label,
		&i.SortOrder,
		&i.ImagePath,
		&i.ImageW,
		&i.ImageH,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFloorPlan = `-- name: DeleteFloorPlan :exec
DELETE FROM floor_plan WHERE id = $1
`

// DELETE /api/floor-plans/:id. Cascades to device_floor_plan_placement (0033).
// Handler writes audit row inside the same tx before committing.
func (q *Queries) DeleteFloorPlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFloorPlan, id)
	return err
}

const getFloorPlan = `-- name: GetFloorPlan :one
SELECT id, site_id, label, sort_order, image_path, image_w, image_h, uploaded_at, updated_at
FROM floor_plan
WHERE id = $1
`

func (q *Queries) GetFloorPlan(ctx context.Context, id pgtype.UUID) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, getFloorPlan, id)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Label,
		&i.SortOrder,
		&i.ImagePath,
		&i.ImageW,
		&i.ImageH,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFloorPlansBySite = `-- name: ListFloorPlansBySite :many
SELECT id, site_id, label, sort_order, image_path, image_w, image_h, uploaded_at, updated_at
FROM floor_plan
WHERE site_id = $1
ORDER BY sort_order, uploaded_at
`

// Site detail — Floor plan tab. Ordered by sort_order then uploaded_at so
// ties resolve deterministically (upload order breaks ties within the same
// sort_order — though UNIQUE prevents true dupes within a site).
func (q *Queries) ListFloorPlansBySite(ctx context.Context, siteID pgtype.UUID) ([]FloorPlan, error) {
	rows, err := q.db.Query(ctx, listFloorPlansBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorPlan
	for rows.Next() {
		var i FloorPlan
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Label,
			&i.SortOrder,
			&i.ImagePath,
			&i.ImageW,
			&i.ImageH,
			&i.UploadedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFloorPlanImage = `-- name: UpdateFloorPlanImage :one
UPDATE floor_plan
SET image_path = $2, image_w = $3, image_h = $4, updated_at = now()
WHERE id = $1
RETURNING id, site_id, label, sort_order, image_path, image_w, image_h, uploaded_at, updated_at
`

type UpdateFloorPlanImageParams struct {
	ID        pgtype.UUID
	ImagePath string
	ImageW    int32
	ImageH    int32
}

// PATCH /api/floor-plans/:id — replaces the image file while keeping the
// label/sort_order and ALL device_floor_plan_placement rows intact (D-24).
// Handler writes the new file, calls UpdateFloorPlanImage, then unlinks the
// old file on commit (on rollback the new file is unlinked).
func (q *Queries) UpdateFloorPlanImage(ctx context.Context, arg UpdateFloorPlanImageParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, updateFloorPlanImage,
		arg.ID,
		arg.ImagePath,
		arg.ImageW,
		arg.ImageH,
	)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Label,
		&i.SortOrder,
		&i.ImagePath,
		&i.ImageW,
		&i.ImageH,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFloorPlanLabel = `-- name: UpdateFloorPlanLabel :one
UPDATE floor_plan
SET label = $2, sort_order = $3, updated_at = now()
WHERE id = $1
RETURNING id, site_id, label, sort_order, image_path, image_w, image_h, uploaded_at, updated_at
`

type UpdateFloorPlanLabelParams struct {
	ID        pgtype.UUID
	Label     string
	SortOrder int32
}

// PATCH /api/floor-plans/:id/label — renames + optionally reorders a plan.
// Conflict on UNIQUE (site_id, sort_order) if another plan already holds the
// new sort_order → handler returns 409.
func (q *Queries) UpdateFloorPlanLabel(ctx context.Context, arg UpdateFloorPlanLabelParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, updateFloorPlanLabel, arg.ID, arg.Label, arg.SortOrder)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Label,
		&i.SortOrder,
		&i.ImagePath,
		&i.ImageW,
		&i.ImageH,
		&i.UploadedAt,
		&i.UpdatedAt,
	)
	return i, err
}
