// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveGateway = `-- name: ArchiveGateway :one
UPDATE gateway SET archived_at = now(), archived_reason = $2, archived_snapshot = $3
WHERE id = $1 AND archived_at IS NULL
RETURNING id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at
`

type ArchiveGatewayParams struct {
	ID               pgtype.UUID
	ArchivedReason   *string
	ArchivedSnapshot []byte
}

// D-30 verbatim (user decision 2026-05-11): soft-delete in Postgres
// (archived_at, archived_reason, archived_snapshot) + ChirpStack
// DeleteGateway called by the handler in the SAME transaction. Snapshot
// preserves the CS proto (protojson) so RestoreGateway can faithfully
// re-create.
func (q *Queries) ArchiveGateway(ctx context.Context, arg ArchiveGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, archiveGateway, arg.ID, arg.ArchivedReason, arg.ArchivedSnapshot)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Tags,
		&i.CsTenantID,
		&i.StatsRefreshedAt,
		&i.StatsRx24h,
		&i.StatsTx24h,
		&i.StatsTxOk24h,
		&i.StatsSparkline,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.ArchivedSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const countGatewaysActive = `-- name: CountGatewaysActive :one
SELECT COUNT(*) FROM gateway WHERE archived_at IS NULL
`

func (q *Queries) CountGatewaysActive(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGatewaysActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGateway = `-- name: CreateGateway :one

INSERT INTO gateway (gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at
`

type CreateGatewayParams struct {
	GatewayID   string
	Name        string
	Description *string
	Region      string
	Lat         *float64
	Lng         *float64
	Altitude    *float64
	Tags        []byte
	CsTenantID  *string
}

// Gateway CRUD + stats cache + decommission. Phase 3 D-29..D-32.
//
// D-30 verbatim (user decision 2026-05-11): soft-delete in Postgres (via
// archived_at + archived_reason + archived_snapshot) is the PG half of the
// atomic decommission tx; the handler issues ChirpStack DeleteGateway in the
// same Serializable tx. archived_snapshot stores the CS Gateway proto as
// JSON so RestoreGateway can faithfully re-create.
//
// Phase 3 simplification: the per-gateway "X devices in last 24h" warning
// count (D-31) is NOT served from a sqlc query here because the measurement
// hypertable (0015_measurement.up.sql) has no `gateway_id` column yet —
// D-31 warning copy ships without device count. Phase 4 telemetry ingest
// adds `measurement.gateway_id` and at that point the count query lands
// alongside this file.
func (q *Queries) CreateGateway(ctx context.Context, arg CreateGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, createGateway,
		arg.GatewayID,
		arg.Name,
		arg.Description,
		arg.Region,
		arg.Lat,
		arg.Lng,
		arg.Altitude,
		arg.Tags,
		arg.CsTenantID,
	)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Tags,
		&i.CsTenantID,
		&i.StatsRefreshedAt,
		&i.StatsRx24h,
		&i.StatsTx24h,
		&i.StatsTxOk24h,
		&i.StatsSparkline,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.ArchivedSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getGateway = `-- name: GetGateway :one
SELECT id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at FROM gateway WHERE id = $1
`

func (q *Queries) GetGateway(ctx context.Context, id pgtype.UUID) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGateway, id)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Tags,
		&i.CsTenantID,
		&i.StatsRefreshedAt,
		&i.StatsRx24h,
		&i.StatsTx24h,
		&i.StatsTxOk24h,
		&i.StatsSparkline,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.ArchivedSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getGatewayByGatewayID = `-- name: GetGatewayByGatewayID :one
SELECT id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at FROM gateway WHERE gateway_id = $1
`

// Lowercase EUI lookup (matches Phase 2 dev_eui pattern). Caller MUST pass
// the lowercase form — the schema CHECK enforces it on storage.
func (q *Queries) GetGatewayByGatewayID(ctx context.Context, gatewayID string) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByGatewayID, gatewayID)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Tags,
		&i.CsTenantID,
		&i.StatsRefreshedAt,
		&i.StatsRx24h,
		&i.StatsTx24h,
		&i.StatsTxOk24h,
		&i.StatsSparkline,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.ArchivedSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listGatewaysActive = `-- name: ListGatewaysActive :many
SELECT id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at FROM gateway
WHERE archived_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListGatewaysActiveParams struct {
	Limit  int32
	Offset int32
}

// D-32 default view: hides archived rows. Phase 3 ships a stable
// created_at DESC ordering (the gateway list is small — ≤200 per page —
// and operator workflows expect "newest first"). The handler exposes
// sort/filter via URL params but currently maps them all to this query;
// richer ordering arrives with the Phase 4 gateway dashboard.
func (q *Queries) ListGatewaysActive(ctx context.Context, arg ListGatewaysActiveParams) ([]Gateway, error) {
	rows, err := q.db.Query(ctx, listGatewaysActive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gateway
	for rows.Next() {
		var i Gateway
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.Name,
			&i.Description,
			&i.Region,
			&i.Lat,
			&i.Lng,
			&i.Altitude,
			&i.Tags,
			&i.CsTenantID,
			&i.StatsRefreshedAt,
			&i.StatsRx24h,
			&i.StatsTx24h,
			&i.StatsTxOk24h,
			&i.StatsSparkline,
			&i.ArchivedAt,
			&i.ArchivedReason,
			&i.ArchivedSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewaysIncludingArchived = `-- name: ListGatewaysIncludingArchived :many
SELECT id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at FROM gateway
ORDER BY archived_at DESC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListGatewaysIncludingArchivedParams struct {
	Limit  int32
	Offset int32
}

// D-32 "Show archived" toggle. archived rows sorted by archived_at DESC
// first, then active rows by created_at DESC.
func (q *Queries) ListGatewaysIncludingArchived(ctx context.Context, arg ListGatewaysIncludingArchivedParams) ([]Gateway, error) {
	rows, err := q.db.Query(ctx, listGatewaysIncludingArchived, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gateway
	for rows.Next() {
		var i Gateway
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.Name,
			&i.Description,
			&i.Region,
			&i.Lat,
			&i.Lng,
			&i.Altitude,
			&i.Tags,
			&i.CsTenantID,
			&i.StatsRefreshedAt,
			&i.StatsRx24h,
			&i.StatsTx24h,
			&i.StatsTxOk24h,
			&i.StatsSparkline,
			&i.ArchivedAt,
			&i.ArchivedReason,
			&i.ArchivedSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreGateway = `-- name: RestoreGateway :one
UPDATE gateway SET archived_at = NULL, archived_reason = NULL, archived_snapshot = NULL
WHERE id = $1 AND archived_at IS NOT NULL
RETURNING id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at
`

// Restore reads archived_snapshot and the handler calls
// chirpstackClient.CreateGateway with it; this UPDATE clears the archive
// columns atomic with the CS recreate.
func (q *Queries) RestoreGateway(ctx context.Context, id pgtype.UUID) (Gateway, error) {
	row := q.db.QueryRow(ctx, restoreGateway, id)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Tags,
		&i.CsTenantID,
		&i.StatsRefreshedAt,
		&i.StatsRx24h,
		&i.StatsTx24h,
		&i.StatsTxOk24h,
		&i.StatsSparkline,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.ArchivedSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateGateway = `-- name: UpdateGateway :one
UPDATE gateway SET
    name = $2,
    description = $3,
    region = $4,
    lat = $5, lng = $6, altitude = $7,
    tags = $8
WHERE id = $1 AND archived_at IS NULL
RETURNING id, gateway_id, name, description, region, lat, lng, altitude, tags, cs_tenant_id, stats_refreshed_at, stats_rx_24h, stats_tx_24h, stats_tx_ok_24h, stats_sparkline, archived_at, archived_reason, archived_snapshot, created_at, updated_at, last_seen_at
`

type UpdateGatewayParams struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	Region      string
	Lat         *float64
	Lng         *float64
	Altitude    *float64
	Tags        []byte
}

func (q *Queries) UpdateGateway(ctx context.Context, arg UpdateGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, updateGateway,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Region,
		arg.Lat,
		arg.Lng,
		arg.Altitude,
		arg.Tags,
	)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Name,
		&i.Description,
		&i.Region,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Tags,
		&i.CsTenantID,
		&i.StatsRefreshedAt,
		&i.StatsRx24h,
		&i.StatsTx24h,
		&i.StatsTxOk24h,
		&i.StatsSparkline,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.ArchivedSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateGatewayStatsCache = `-- name: UpdateGatewayStatsCache :exec
UPDATE gateway SET
    stats_refreshed_at = now(),
    stats_rx_24h       = $2,
    stats_tx_24h       = $3,
    stats_tx_ok_24h    = $4,
    stats_sparkline    = $5,
    last_seen_at       = $6
WHERE id = $1
`

type UpdateGatewayStatsCacheParams struct {
	ID             pgtype.UUID
	StatsRx24h     *int64
	StatsTx24h     *int64
	StatsTxOk24h   *int64
	StatsSparkline []byte
	LastSeenAt     pgtype.Timestamptz
}

// Called by cache_refresher.go after a successful GetMetrics fetch (D-02).
// $6 is the chirpstack-reported last_seen_at (NULL when never_seen). Keeping
// last_seen_at on the same cache row means a single read covers status badge
// + 24h stats for the gateway list page (no separate query path).
func (q *Queries) UpdateGatewayStatsCache(ctx context.Context, arg UpdateGatewayStatsCacheParams) error {
	_, err := q.db.Exec(ctx, updateGatewayStatsCache,
		arg.ID,
		arg.StatsRx24h,
		arg.StatsTx24h,
		arg.StatsTxOk24h,
		arg.StatsSparkline,
		arg.LastSeenAt,
	)
	return err
}
