// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImportJobRows = `-- name: CountImportJobRows :one
SELECT COUNT(*) FROM import_job_row WHERE import_job_id = $1
`

func (q *Queries) CountImportJobRows(ctx context.Context, importJobID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobRows, importJobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImportJobs = `-- name: CountImportJobs :one
SELECT COUNT(*) FROM import_job
`

func (q *Queries) CountImportJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImportJob = `-- name: CreateImportJob :one

INSERT INTO import_job (job_id, owner_id, file_name, file_format, total_rows, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at
`

type CreateImportJobParams struct {
	JobID      pgtype.UUID
	OwnerID    pgtype.UUID
	FileName   string
	FileFormat string
	TotalRows  int32
	ExpiresAt  pgtype.Timestamptz
}

// Bulk-import job state machine + per-row outcomes. Phase 3 D-04..D-11.
//
// D-11 TTL 1h on preview; D-34 job_id used as audit request_id; D-35 90-day
// retention. Per-row raw_payload JSONB preserves the original file for
// errors.xlsx round-trip.
// Plan 03-05 upload handler: creates the preview job. total_rows + expires_at
// supplied by handler (now+1h).
func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.JobID,
		arg.OwnerID,
		arg.FileName,
		arg.FileFormat,
		arg.TotalRows,
		arg.ExpiresAt,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OwnerID,
		&i.FileName,
		&i.FileFormat,
		&i.TotalRows,
		&i.Status,
		&i.ValidCount,
		&i.InvalidCount,
		&i.AlreadyExistsCount,
		&i.CreatedCount,
		&i.FailedCount,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at FROM import_job WHERE id = $1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id pgtype.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OwnerID,
		&i.FileName,
		&i.FileFormat,
		&i.TotalRows,
		&i.Status,
		&i.ValidCount,
		&i.InvalidCount,
		&i.AlreadyExistsCount,
		&i.CreatedCount,
		&i.FailedCount,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportJobByJobID = `-- name: GetImportJobByJobID :one
SELECT id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at FROM import_job WHERE job_id = $1
`

// External-facing lookup (paths use the publicly-shared job_id UUID).
func (q *Queries) GetImportJobByJobID(ctx context.Context, jobID pgtype.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByJobID, jobID)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OwnerID,
		&i.FileName,
		&i.FileFormat,
		&i.TotalRows,
		&i.Status,
		&i.ValidCount,
		&i.InvalidCount,
		&i.AlreadyExistsCount,
		&i.CreatedCount,
		&i.FailedCount,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertImportJobRow = `-- name: InsertImportJobRow :one
INSERT INTO import_job_row (import_job_id, row_index, raw_payload, parsed, status, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, import_job_id, row_index, raw_payload, parsed, status, reason, created_device_id
`

type InsertImportJobRowParams struct {
	ImportJobID pgtype.UUID
	RowIndex    int32
	RawPayload  []byte
	Parsed      []byte
	Status      ImportJobRowStatus
	Reason      *string
}

// Per-row outcome row from dry-run (status ∈ valid|invalid|already_exists).
// Commit pass later UPDATEs the row to created|failed via
// UpdateImportJobRowOutcome.
func (q *Queries) InsertImportJobRow(ctx context.Context, arg InsertImportJobRowParams) (ImportJobRow, error) {
	row := q.db.QueryRow(ctx, insertImportJobRow,
		arg.ImportJobID,
		arg.RowIndex,
		arg.RawPayload,
		arg.Parsed,
		arg.Status,
		arg.Reason,
	)
	var i ImportJobRow
	err := row.Scan(
		&i.ID,
		&i.ImportJobID,
		&i.RowIndex,
		&i.RawPayload,
		&i.Parsed,
		&i.Status,
		&i.Reason,
		&i.CreatedDeviceID,
	)
	return i, err
}

const listImportJobErrorRows = `-- name: ListImportJobErrorRows :many
SELECT id, import_job_id, row_index, raw_payload, parsed, status, reason, created_device_id FROM import_job_row
WHERE import_job_id = $1
  AND status IN ('invalid', 'failed')
ORDER BY row_index ASC
`

// Used by errors.xlsx generator. Returns only invalid + failed rows so the
// operator gets back the cells that need fixing plus the reason.
func (q *Queries) ListImportJobErrorRows(ctx context.Context, importJobID pgtype.UUID) ([]ImportJobRow, error) {
	rows, err := q.db.Query(ctx, listImportJobErrorRows, importJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJobRow
	for rows.Next() {
		var i ImportJobRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportJobID,
			&i.RowIndex,
			&i.RawPayload,
			&i.Parsed,
			&i.Status,
			&i.Reason,
			&i.CreatedDeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobRows = `-- name: ListImportJobRows :many
SELECT id, import_job_id, row_index, raw_payload, parsed, status, reason, created_device_id FROM import_job_row
WHERE import_job_id = $1
ORDER BY row_index ASC
LIMIT $2 OFFSET $3
`

type ListImportJobRowsParams struct {
	ImportJobID pgtype.UUID
	Limit       int32
	Offset      int32
}

// Paginated job-detail page. Ordered by row_index so the UI shows file order.
func (q *Queries) ListImportJobRows(ctx context.Context, arg ListImportJobRowsParams) ([]ImportJobRow, error) {
	rows, err := q.db.Query(ctx, listImportJobRows, arg.ImportJobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJobRow
	for rows.Next() {
		var i ImportJobRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportJobID,
			&i.RowIndex,
			&i.RawPayload,
			&i.Parsed,
			&i.Status,
			&i.Reason,
			&i.CreatedDeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobs = `-- name: ListImportJobs :many
SELECT id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at FROM import_job
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListImportJobsParams struct {
	Limit  int32
	Offset int32
}

// Phase 3 D-36 "/admin/imports" page. Newest first.
func (q *Queries) ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportJob
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.OwnerID,
			&i.FileName,
			&i.FileFormat,
			&i.TotalRows,
			&i.Status,
			&i.ValidCount,
			&i.InvalidCount,
			&i.AlreadyExistsCount,
			&i.CreatedCount,
			&i.FailedCount,
			&i.ExpiresAt,
			&i.CommittedAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportJobCounters = `-- name: UpdateImportJobCounters :one
UPDATE import_job SET
    total_rows = $2,
    valid_count = $3,
    invalid_count = $4,
    already_exists_count = $5
WHERE id = $1
RETURNING id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at
`

type UpdateImportJobCountersParams struct {
	ID                 pgtype.UUID
	TotalRows          int32
	ValidCount         int32
	InvalidCount       int32
	AlreadyExistsCount int32
}

// Upload handler bulk-update after dry-run validation runs. Counter values
// supplied directly so the handler doesn't have to issue per-status COUNT(*)
// queries against import_job_row.
func (q *Queries) UpdateImportJobCounters(ctx context.Context, arg UpdateImportJobCountersParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobCounters,
		arg.ID,
		arg.TotalRows,
		arg.ValidCount,
		arg.InvalidCount,
		arg.AlreadyExistsCount,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OwnerID,
		&i.FileName,
		&i.FileFormat,
		&i.TotalRows,
		&i.Status,
		&i.ValidCount,
		&i.InvalidCount,
		&i.AlreadyExistsCount,
		&i.CreatedCount,
		&i.FailedCount,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportJobRowOutcome = `-- name: UpdateImportJobRowOutcome :one
UPDATE import_job_row SET
    status = $2,
    reason = $3,
    created_device_id = $4
WHERE id = $1
RETURNING id, import_job_id, row_index, raw_payload, parsed, status, reason, created_device_id
`

type UpdateImportJobRowOutcomeParams struct {
	ID              int64
	Status          ImportJobRowStatus
	Reason          *string
	CreatedDeviceID pgtype.UUID
}

// Commit pass writes the final outcome (created / failed) + the
// created_device_id pointer so audit-replay can correlate rows to device rows.
func (q *Queries) UpdateImportJobRowOutcome(ctx context.Context, arg UpdateImportJobRowOutcomeParams) (ImportJobRow, error) {
	row := q.db.QueryRow(ctx, updateImportJobRowOutcome,
		arg.ID,
		arg.Status,
		arg.Reason,
		arg.CreatedDeviceID,
	)
	var i ImportJobRow
	err := row.Scan(
		&i.ID,
		&i.ImportJobID,
		&i.RowIndex,
		&i.RawPayload,
		&i.Parsed,
		&i.Status,
		&i.Reason,
		&i.CreatedDeviceID,
	)
	return i, err
}

const updateImportJobToCommitted = `-- name: UpdateImportJobToCommitted :one
UPDATE import_job SET
    status = 'committed',
    committed_at = now(),
    created_count = $2,
    already_exists_count = $3,
    failed_count = $4,
    invalid_count = $5,
    valid_count = $6,
    expires_at = NULL
WHERE id = $1 AND status = 'preview'
RETURNING id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at
`

type UpdateImportJobToCommittedParams struct {
	ID                 pgtype.UUID
	CreatedCount       int32
	AlreadyExistsCount int32
	FailedCount        int32
	InvalidCount       int32
	ValidCount         int32
}

// Commit-handler terminal state. expires_at cleared so the partial-cleanup
// sweeper (Phase 9) doesn't touch committed rows.
func (q *Queries) UpdateImportJobToCommitted(ctx context.Context, arg UpdateImportJobToCommittedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobToCommitted,
		arg.ID,
		arg.CreatedCount,
		arg.AlreadyExistsCount,
		arg.FailedCount,
		arg.InvalidCount,
		arg.ValidCount,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OwnerID,
		&i.FileName,
		&i.FileFormat,
		&i.TotalRows,
		&i.Status,
		&i.ValidCount,
		&i.InvalidCount,
		&i.AlreadyExistsCount,
		&i.CreatedCount,
		&i.FailedCount,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportJobToExpired = `-- name: UpdateImportJobToExpired :one
UPDATE import_job SET status = 'expired'
WHERE id = $1 AND status = 'preview' AND expires_at < now()
RETURNING id, job_id, owner_id, file_name, file_format, total_rows, status, valid_count, invalid_count, already_exists_count, created_count, failed_count, expires_at, committed_at, failed_reason, created_at, updated_at
`

// D-11: lazy expiry on read. Only transitions preview→expired when the
// expires_at deadline has passed.
func (q *Queries) UpdateImportJobToExpired(ctx context.Context, id pgtype.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobToExpired, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OwnerID,
		&i.FileName,
		&i.FileFormat,
		&i.TotalRows,
		&i.Status,
		&i.ValidCount,
		&i.InvalidCount,
		&i.AlreadyExistsCount,
		&i.CreatedCount,
		&i.FailedCount,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
