// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: install_identity.sql

package sqlc

import (
	"context"
)

const getInstallIdentity = `-- name: GetInstallIdentity :one
SELECT id, display_name, logo_path, address, timezone, units, created_at, updated_at FROM install_identity WHERE id = 1
`

func (q *Queries) GetInstallIdentity(ctx context.Context) (InstallIdentity, error) {
	row := q.db.QueryRow(ctx, getInstallIdentity)
	var i InstallIdentity
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.LogoPath,
		&i.Address,
		&i.Timezone,
		&i.Units,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInstallIdentity = `-- name: UpsertInstallIdentity :one
INSERT INTO install_identity (id, display_name, logo_path, address, timezone, units)
VALUES (1, $1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    logo_path    = EXCLUDED.logo_path,
    address      = EXCLUDED.address,
    timezone     = EXCLUDED.timezone,
    units        = EXCLUDED.units
RETURNING id, display_name, logo_path, address, timezone, units, created_at, updated_at
`

type UpsertInstallIdentityParams struct {
	DisplayName string
	LogoPath    *string
	Address     *string
	Timezone    string
	Units       UnitsSystem
}

// Plan 15 wizard finish + Phase 5 settings page edit.
func (q *Queries) UpsertInstallIdentity(ctx context.Context, arg UpsertInstallIdentityParams) (InstallIdentity, error) {
	row := q.db.QueryRow(ctx, upsertInstallIdentity,
		arg.DisplayName,
		arg.LogoPath,
		arg.Address,
		arg.Timezone,
		arg.Units,
	)
	var i InstallIdentity
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.LogoPath,
		&i.Address,
		&i.Timezone,
		&i.Units,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
