// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: install_state.sql

package sqlc

import (
	"context"
)

const deleteInstallState = `-- name: DeleteInstallState :exec
DELETE FROM install_state WHERE id = 1
`

// Called by FinishSetup after all four target tables are populated.
func (q *Queries) DeleteInstallState(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteInstallState)
	return err
}

const getOrCreateInstallState = `-- name: GetOrCreateInstallState :one
INSERT INTO install_state (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET id = 1
RETURNING id, started_at, completed_at, current_step, step1_admin, step2_chirpstack, step3_region, step4_identity, updated_at
`

// Plan 15 reentrant wizard: GET /api/install/state returns the singleton row,
// creating it on first call.
func (q *Queries) GetOrCreateInstallState(ctx context.Context) (InstallState, error) {
	row := q.db.QueryRow(ctx, getOrCreateInstallState)
	var i InstallState
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CurrentStep,
		&i.Step1Admin,
		&i.Step2Chirpstack,
		&i.Step3Region,
		&i.Step4Identity,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStep1 = `-- name: UpdateStep1 :exec
UPDATE install_state
SET step1_admin = $1,
    current_step = GREATEST(current_step, 2)
WHERE id = 1
`

func (q *Queries) UpdateStep1(ctx context.Context, step1Admin []byte) error {
	_, err := q.db.Exec(ctx, updateStep1, step1Admin)
	return err
}

const updateStep2 = `-- name: UpdateStep2 :exec
UPDATE install_state
SET step2_chirpstack = $1,
    current_step = GREATEST(current_step, 3)
WHERE id = 1
`

func (q *Queries) UpdateStep2(ctx context.Context, step2Chirpstack []byte) error {
	_, err := q.db.Exec(ctx, updateStep2, step2Chirpstack)
	return err
}

const updateStep3 = `-- name: UpdateStep3 :exec
UPDATE install_state
SET step3_region = $1,
    current_step = GREATEST(current_step, 4)
WHERE id = 1
`

func (q *Queries) UpdateStep3(ctx context.Context, step3Region []byte) error {
	_, err := q.db.Exec(ctx, updateStep3, step3Region)
	return err
}

const updateStep4 = `-- name: UpdateStep4 :exec
UPDATE install_state
SET step4_identity = $1,
    current_step = GREATEST(current_step, 5)
WHERE id = 1
`

func (q *Queries) UpdateStep4(ctx context.Context, step4Identity []byte) error {
	_, err := q.db.Exec(ctx, updateStep4, step4Identity)
	return err
}
