// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metering_points.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveMP = `-- name: ArchiveMP :one
UPDATE metering_point SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at
`

// D-20 soft-delete. Idempotent guard.
func (q *Queries) ArchiveMP(ctx context.Context, id pgtype.UUID) (MeteringPoint, error) {
	row := q.db.QueryRow(ctx, archiveMP, id)
	var i MeteringPoint
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.UtilityClass,
		&i.LocationDescription,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMP = `-- name: CreateMP :one

INSERT INTO metering_point (site_id, name, utility_class, location_description)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at
`

type CreateMPParams struct {
	SiteID              pgtype.UUID
	Name                string
	UtilityClass        string
	LocationDescription *string
}

// Metering Point (D-19 + D-20) — the canonical "thing being measured" that
// persists across physical meter swaps (DATA-01 invariant). MP is the join
// key for telemetry; binding history captures which device fed it when.
// Plan 02-08 MP create dialog. (site_id, name) UNIQUE constraint surfaces
// as a 23505 error to the caller — handler maps to a friendly toast.
func (q *Queries) CreateMP(ctx context.Context, arg CreateMPParams) (MeteringPoint, error) {
	row := q.db.QueryRow(ctx, createMP,
		arg.SiteID,
		arg.Name,
		arg.UtilityClass,
		arg.LocationDescription,
	)
	var i MeteringPoint
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.UtilityClass,
		&i.LocationDescription,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMP = `-- name: GetMP :one
SELECT id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at FROM metering_point WHERE id = $1
`

func (q *Queries) GetMP(ctx context.Context, id pgtype.UUID) (MeteringPoint, error) {
	row := q.db.QueryRow(ctx, getMP, id)
	var i MeteringPoint
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.UtilityClass,
		&i.LocationDescription,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMPWithActiveBinding = `-- name: GetMPWithActiveBinding :one
SELECT mp.id, mp.site_id, mp.name, mp.utility_class, mp.location_description,
       mp.archived_at, mp.created_at, mp.updated_at,
       b.id  AS binding_id,
       b.device_id,
       b.valid_from AS binding_valid_from,
       b.reading_offset,
       d.dev_eui,
       d.name AS device_name,
       dp.id AS device_profile_id,
       dp.name AS device_profile_name,
       dp.capabilities,
       dp.counter_modulus
FROM metering_point mp
LEFT JOIN binding         b  ON b.metering_point_id = mp.id AND b.valid_to IS NULL
LEFT JOIN device          d  ON d.id = b.device_id
LEFT JOIN device_profile  dp ON dp.id = d.device_profile_id
WHERE mp.id = $1
`

type GetMPWithActiveBindingRow struct {
	ID                  pgtype.UUID
	SiteID              pgtype.UUID
	Name                string
	UtilityClass        string
	LocationDescription *string
	ArchivedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	BindingID           pgtype.UUID
	DeviceID            pgtype.UUID
	BindingValidFrom    pgtype.Timestamptz
	ReadingOffset       pgtype.Numeric
	DevEui              *string
	DeviceName          *string
	DeviceProfileID     pgtype.UUID
	DeviceProfileName   *string
	Capabilities        []string
	CounterModulus      *int64
}

// MP detail page (Plan 02-08): shows "currently bound device + reading offset".
// LEFT JOINs return NULL for binding/device/profile columns when no active
// binding exists (a fresh MP that hasn't been wired up yet, or a swap-in-
// progress where the previous binding closed and the next hasn't opened).
func (q *Queries) GetMPWithActiveBinding(ctx context.Context, id pgtype.UUID) (GetMPWithActiveBindingRow, error) {
	row := q.db.QueryRow(ctx, getMPWithActiveBinding, id)
	var i GetMPWithActiveBindingRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.UtilityClass,
		&i.LocationDescription,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BindingID,
		&i.DeviceID,
		&i.BindingValidFrom,
		&i.ReadingOffset,
		&i.DevEui,
		&i.DeviceName,
		&i.DeviceProfileID,
		&i.DeviceProfileName,
		&i.Capabilities,
		&i.CounterModulus,
	)
	return i, err
}

const listActiveMPs = `-- name: ListActiveMPs :many
SELECT id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at FROM metering_point WHERE archived_at IS NULL ORDER BY name ASC
`

// Global MP list (rare — usually scoped by site). archived_at filter hits the
// partial index.
func (q *Queries) ListActiveMPs(ctx context.Context) ([]MeteringPoint, error) {
	rows, err := q.db.Query(ctx, listActiveMPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeteringPoint
	for rows.Next() {
		var i MeteringPoint
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.UtilityClass,
			&i.LocationDescription,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedMPs = `-- name: ListArchivedMPs :many
SELECT id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at FROM metering_point WHERE archived_at IS NOT NULL ORDER BY archived_at DESC
`

func (q *Queries) ListArchivedMPs(ctx context.Context) ([]MeteringPoint, error) {
	rows, err := q.db.Query(ctx, listArchivedMPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeteringPoint
	for rows.Next() {
		var i MeteringPoint
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.UtilityClass,
			&i.LocationDescription,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMPsBySite = `-- name: ListMPsBySite :many
SELECT id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at FROM metering_point
WHERE site_id = $1 AND archived_at IS NULL
ORDER BY name ASC
`

// Site detail MP-list section. Active-only by default; site_idx covers the
// filter, archived_at NULL is the common case.
func (q *Queries) ListMPsBySite(ctx context.Context, siteID pgtype.UUID) ([]MeteringPoint, error) {
	rows, err := q.db.Query(ctx, listMPsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeteringPoint
	for rows.Next() {
		var i MeteringPoint
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.UtilityClass,
			&i.LocationDescription,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreMP = `-- name: RestoreMP :one
UPDATE metering_point SET archived_at = NULL
WHERE id = $1 AND archived_at IS NOT NULL
RETURNING id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at
`

func (q *Queries) RestoreMP(ctx context.Context, id pgtype.UUID) (MeteringPoint, error) {
	row := q.db.QueryRow(ctx, restoreMP, id)
	var i MeteringPoint
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.UtilityClass,
		&i.LocationDescription,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMP = `-- name: UpdateMP :one
UPDATE metering_point SET
    name = $2, utility_class = $3, location_description = $4
WHERE id = $1
RETURNING id, site_id, name, utility_class, location_description, archived_at, created_at, updated_at
`

type UpdateMPParams struct {
	ID                  pgtype.UUID
	Name                string
	UtilityClass        string
	LocationDescription *string
}

// Plan 02-08 MP edit. utility_class IS editable here (operators sometimes
// mis-classify; the CHECK constraint still bounds the values to water |
// electricity).
func (q *Queries) UpdateMP(ctx context.Context, arg UpdateMPParams) (MeteringPoint, error) {
	row := q.db.QueryRow(ctx, updateMP,
		arg.ID,
		arg.Name,
		arg.UtilityClass,
		arg.LocationDescription,
	)
	var i MeteringPoint
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.UtilityClass,
		&i.LocationDescription,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
