// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChirpstackMode string

const (
	ChirpstackModeBundled  ChirpstackMode = "bundled"
	ChirpstackModeExternal ChirpstackMode = "external"
)

func (e *ChirpstackMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChirpstackMode(s)
	case string:
		*e = ChirpstackMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ChirpstackMode: %T", src)
	}
	return nil
}

type NullChirpstackMode struct {
	ChirpstackMode ChirpstackMode
	Valid          bool // Valid is true if ChirpstackMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChirpstackMode) Scan(value interface{}) error {
	if value == nil {
		ns.ChirpstackMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChirpstackMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChirpstackMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChirpstackMode), nil
}

type UnitsSystem string

const (
	UnitsSystemMetric   UnitsSystem = "metric"
	UnitsSystemImperial UnitsSystem = "imperial"
)

func (e *UnitsSystem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitsSystem(s)
	case string:
		*e = UnitsSystem(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitsSystem: %T", src)
	}
	return nil
}

type NullUnitsSystem struct {
	UnitsSystem UnitsSystem
	Valid       bool // Valid is true if UnitsSystem is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitsSystem) Scan(value interface{}) error {
	if value == nil {
		ns.UnitsSystem, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitsSystem.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitsSystem) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitsSystem), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleViewer UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID         pgtype.UUID
	Time       pgtype.Timestamptz
	UserID     pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	Before     []byte
	After      []byte
	Notes      *string
	RequestID  *string
}

type Binding struct {
	ID              pgtype.UUID
	MeteringPointID pgtype.UUID
	DeviceID        pgtype.UUID
	ValidFrom       pgtype.Timestamptz
	ValidTo         pgtype.Timestamptz
	ReadingOffset   pgtype.Numeric
	LastRawValue    pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
}

type ChirpstackConnection struct {
	ID               int32
	Mode             ChirpstackMode
	GrpcUrl          string
	ApiTokenRef      string
	MqttUrl          string
	MqttUser         *string
	MqttPasswordRef  *string
	RegionName       string
	RegionCommonName string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CsTenantID       *string
	CsApplicationID  *string
}

type Device struct {
	ID               pgtype.UUID
	DevEui           string
	Name             string
	DeviceProfileID  pgtype.UUID
	CsDeviceUuid     *string
	JoinEui          *string
	Description      *string
	LastSeenAt       pgtype.Timestamptz
	DecommissionedAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type DeviceProfile struct {
	ID              pgtype.UUID
	Slug            string
	Name            string
	Vendor          string
	Family          *string
	Capabilities    []string
	CounterModulus  int64
	CodecJs         string
	CsProfileID     pgtype.UUID
	CodecJsSyncedAt pgtype.Timestamptz
	Region          *string
	MacVersion      string
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type DeviceProfileMapping struct {
	ID              pgtype.UUID
	DeviceProfileID pgtype.UUID
	JsonPointer     string
	Target          string
	Scale           pgtype.Numeric
	DataType        string
	Position        int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type InstallIdentity struct {
	ID          int32
	DisplayName string
	LogoPath    *string
	Address     *string
	Timezone    string
	Units       UnitsSystem
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type InstallState struct {
	ID              int32
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	CurrentStep     int16
	Step1Admin      []byte
	Step2Chirpstack []byte
	Step3Region     []byte
	Step4Identity   []byte
	UpdatedAt       pgtype.Timestamptz
}

type Measurement struct {
	Time            pgtype.Timestamptz
	MeteringPointID pgtype.UUID
	RawValue        pgtype.Numeric
	CumulativeValue pgtype.Numeric
	InstantValue    pgtype.Numeric
	BatteryPct      *int16
	Rssi            *int16
	Snr             *float32
	TemperatureC    *float32
	PressureKpa     *float32
	LeakDetected    *bool
	TamperDetected  *bool
	Extra           []byte
	RawPayload      []byte
	DecodedObject   []byte
	Quality         string
	Fcnt            *int32
	GatewayRxTime   pgtype.Timestamptz
	DeviceTime      pgtype.Timestamptz
	BindingID       pgtype.UUID
}

type MeteringPoint struct {
	ID                  pgtype.UUID
	SiteID              pgtype.UUID
	Name                string
	UtilityClass        string
	LocationDescription *string
	ArchivedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Site struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	SiteType    *string
	Lat         *float64
	Lng         *float64
	Timezone    string
	Address     *string
	Description *string
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	Email              string
	Name               string
	PasswordHash       string
	Role               UserRole
	MustChangePassword bool
	DisabledAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
