// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChirpstackMode string

const (
	ChirpstackModeBundled  ChirpstackMode = "bundled"
	ChirpstackModeExternal ChirpstackMode = "external"
)

func (e *ChirpstackMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChirpstackMode(s)
	case string:
		*e = ChirpstackMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ChirpstackMode: %T", src)
	}
	return nil
}

type NullChirpstackMode struct {
	ChirpstackMode ChirpstackMode
	Valid          bool // Valid is true if ChirpstackMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChirpstackMode) Scan(value interface{}) error {
	if value == nil {
		ns.ChirpstackMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChirpstackMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChirpstackMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChirpstackMode), nil
}

type UnitsSystem string

const (
	UnitsSystemMetric   UnitsSystem = "metric"
	UnitsSystemImperial UnitsSystem = "imperial"
)

func (e *UnitsSystem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitsSystem(s)
	case string:
		*e = UnitsSystem(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitsSystem: %T", src)
	}
	return nil
}

type NullUnitsSystem struct {
	UnitsSystem UnitsSystem
	Valid       bool // Valid is true if UnitsSystem is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitsSystem) Scan(value interface{}) error {
	if value == nil {
		ns.UnitsSystem, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitsSystem.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitsSystem) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitsSystem), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleViewer UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ChirpstackConnection struct {
	ID               int32
	Mode             ChirpstackMode
	GrpcUrl          string
	ApiTokenRef      string
	MqttUrl          string
	MqttUser         *string
	MqttPasswordRef  *string
	RegionName       string
	RegionCommonName string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type InstallIdentity struct {
	ID          int32
	DisplayName string
	LogoPath    *string
	Address     *string
	Timezone    string
	Units       UnitsSystem
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type InstallState struct {
	ID              int32
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	CurrentStep     int16
	Step1Admin      []byte
	Step2Chirpstack []byte
	Step3Region     []byte
	Step4Identity   []byte
	UpdatedAt       pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	Email              string
	Name               string
	PasswordHash       string
	Role               UserRole
	MustChangePassword bool
	DisabledAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
