// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// Plan 14 first-run gate: returns TRUE if at least one enabled admin exists.
	AdminExists(ctx context.Context) (bool, error)
	// Called by FinishSetup after all four target tables are populated.
	DeleteInstallState(ctx context.Context) error
	GetChirpStackConnection(ctx context.Context) (ChirpstackConnection, error)
	GetInstallIdentity(ctx context.Context) (InstallIdentity, error)
	// Plan 15 reentrant wizard: GET /api/install/state returns the singleton row,
	// creating it on first call.
	GetOrCreateInstallState(ctx context.Context) (InstallState, error)
	// Plan 09 (login). Email must already be lower()'d by the caller — the
	// 0002_users CHECK enforces it but we don't want to lose the index hit.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Plan 15 install wizard finish — creates the bootstrap admin atomically with
	// the rest of the wizard commit.
	InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (InsertAdminUserRow, error)
	UpdateStep1(ctx context.Context, step1Admin []byte) error
	UpdateStep2(ctx context.Context, step2Chirpstack []byte) error
	UpdateStep3(ctx context.Context, step3Region []byte) error
	UpdateStep4(ctx context.Context, step4Identity []byte) error
	// Plan 11 account UI: change-password flow.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Plan 15 wizard finish + Phase 5 settings page edit.
	UpsertChirpStackConnection(ctx context.Context, arg UpsertChirpStackConnectionParams) (ChirpstackConnection, error)
	// Plan 15 wizard finish + Phase 5 settings page edit.
	UpsertInstallIdentity(ctx context.Context, arg UpsertInstallIdentityParams) (InstallIdentity, error)
}

var _ Querier = (*Queries)(nil)
