// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReportTemplate = `-- name: CreateReportTemplate :one
INSERT INTO report_template (name, description, state, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, state, created_by, created_at, updated_at
`

type CreateReportTemplateParams struct {
	Name        string
	Description string
	State       []byte
	CreatedBy   pgtype.UUID
}

// Inserts a new report template and returns the full row.
// The UNIQUE constraint on name means a duplicate raises pgconn error 23505 (unique_violation).
// Caller maps 23505 → HTTP 409.
func (q *Queries) CreateReportTemplate(ctx context.Context, arg CreateReportTemplateParams) (ReportTemplate, error) {
	row := q.db.QueryRow(ctx, createReportTemplate,
		arg.Name,
		arg.Description,
		arg.State,
		arg.CreatedBy,
	)
	var i ReportTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReportTemplate = `-- name: DeleteReportTemplate :exec
DELETE FROM report_template
WHERE id = $1
`

// Hard-deletes a report template by primary key.
// Caller checks rows-affected = 0 → 404.
func (q *Queries) DeleteReportTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReportTemplate, id)
	return err
}

const getReportTemplate = `-- name: GetReportTemplate :one
SELECT id, name, description, state, created_by, created_at, updated_at
FROM report_template
WHERE id = $1
`

// Fetches a single report template by UUID primary key.
// Returns pgx.ErrNoRows when the template does not exist.
func (q *Queries) GetReportTemplate(ctx context.Context, id pgtype.UUID) (ReportTemplate, error) {
	row := q.db.QueryRow(ctx, getReportTemplate, id)
	var i ReportTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportTemplates = `-- name: ListReportTemplates :many

SELECT id, name, description, state, created_by, created_at, updated_at
FROM report_template
ORDER BY lower(name) ASC
`

// report_templates.sql — Phase 7 Plan 11a: Saved Report Templates (UX-POWER Surface 6).
//
// All 5 queries target the report_template table added by migration 0053.
// RBAC enforcement is at the HTTP handler layer; these queries have no auth logic.
// Returns all report templates ordered case-insensitively by name ascending.
// The lower(name) functional index (0053) makes this sort O(log N).
func (q *Queries) ListReportTemplates(ctx context.Context) ([]ReportTemplate, error) {
	rows, err := q.db.Query(ctx, listReportTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportTemplate
	for rows.Next() {
		var i ReportTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.State,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportTemplate = `-- name: UpdateReportTemplate :exec
UPDATE report_template
SET name        = $2,
    description = $3,
    state       = $4,
    updated_at  = now()
WHERE id = $1
`

type UpdateReportTemplateParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	State       []byte
}

// Updates name, description, and state for an existing template.
// Caller checks rows-affected = 0 → 404.
// Duplicate name on rename raises pgconn 23505 → caller maps to HTTP 409.
func (q *Queries) UpdateReportTemplate(ctx context.Context, arg UpdateReportTemplateParams) error {
	_, err := q.db.Exec(ctx, updateReportTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.State,
	)
	return err
}
