// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one


INSERT INTO report (id, user_id, scope, site_id, metering_point_id, group_by, range_kind, range_start, range_end, artifact_dir, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, scope, site_id, metering_point_id, group_by, range_kind, range_start, range_end, artifact_dir, pdf_status, pdf_path, created_at, expires_at
`

type CreateReportParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Scope           string
	SiteID          pgtype.UUID
	MeteringPointID pgtype.UUID
	GroupBy         *string
	RangeKind       string
	RangeStart      pgtype.Timestamptz
	RangeEnd        pgtype.Timestamptz
	ArtifactDir     string
	ExpiresAt       pgtype.Timestamptz
}

// reports.sql
// sqlc-annotated queries for the Phase 5 report system (REPT-01..07).
// All data queries hit CAGGs (measurement_hourly/daily/monthly/yearly),
// NEVER raw measurement (90d+ raw queries are expensive per Phase 4 D-12).
//
// Range → CAGG mapping (must_haves truth #6):
//
//	range=daily   → measurement_hourly (bucketed to days in query)
//	range=monthly → measurement_daily  (bucketed to months in query)
//	range=yearly  → measurement_monthly (bucketed to years in query)
//
// -------- REPORT METADATA CRUD ----------
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.UserID,
		arg.Scope,
		arg.SiteID,
		arg.MeteringPointID,
		arg.GroupBy,
		arg.RangeKind,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ArtifactDir,
		arg.ExpiresAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.SiteID,
		&i.MeteringPointID,
		&i.GroupBy,
		&i.RangeKind,
		&i.RangeStart,
		&i.RangeEnd,
		&i.ArtifactDir,
		&i.PdfStatus,
		&i.PdfPath,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, user_id, scope, site_id, metering_point_id, group_by, range_kind, range_start, range_end, artifact_dir, pdf_status, pdf_path, created_at, expires_at FROM report WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.SiteID,
		&i.MeteringPointID,
		&i.GroupBy,
		&i.RangeKind,
		&i.RangeStart,
		&i.RangeEnd,
		&i.ArtifactDir,
		&i.PdfStatus,
		&i.PdfPath,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredReports = `-- name: ListExpiredReports :many
SELECT id, artifact_dir FROM report
WHERE expires_at < now() AND pdf_status <> 'expired'
`

type ListExpiredReportsRow struct {
	ID          pgtype.UUID
	ArtifactDir string
}

func (q *Queries) ListExpiredReports(ctx context.Context) ([]ListExpiredReportsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredReportsRow
	for rows.Next() {
		var i ListExpiredReportsRow
		if err := rows.Scan(&i.ID, &i.ArtifactDir); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetersInScope = `-- name: ListMetersInScope :many
SELECT
  mp.id,
  mp.name,
  mp.utility_class,
  mp.site_id,
  s.name AS site_name
FROM metering_point mp
JOIN site s ON s.id = mp.site_id
WHERE
  ($1::TEXT = 'all') OR
  ($1::TEXT = 'site' AND mp.site_id = $2) OR
  ($1::TEXT = 'meter' AND mp.id = $3)
ORDER BY s.name, mp.name
`

type ListMetersInScopeParams struct {
	Column1 string
	SiteID  pgtype.UUID
	ID      pgtype.UUID
}

type ListMetersInScopeRow struct {
	ID           pgtype.UUID
	Name         string
	UtilityClass string
	SiteID       pgtype.UUID
	SiteName     string
}

// Returns metering points in scope (all / site / single) for the meter_rows table.
func (q *Queries) ListMetersInScope(ctx context.Context, arg ListMetersInScopeParams) ([]ListMetersInScopeRow, error) {
	rows, err := q.db.Query(ctx, listMetersInScope, arg.Column1, arg.SiteID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetersInScopeRow
	for rows.Next() {
		var i ListMetersInScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UtilityClass,
			&i.SiteID,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportExpired = `-- name: MarkReportExpired :exec
UPDATE report SET pdf_status = 'expired' WHERE id = $1
`

func (q *Queries) MarkReportExpired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReportExpired, id)
	return err
}

const reportDailyByCategory = `-- name: ReportDailyByCategory :many
SELECT
  time_bucket('1 day', mh.bucket) AS period,
  mp.utility_class,
  round(coalesce(sum(mh.cumulative_delta), 0))::bigint        AS consumption
FROM measurement_hourly mh
JOIN metering_point mp ON mp.id = mh.metering_point_id
WHERE mh.bucket >= $1 AND mh.bucket < $2
GROUP BY 1, 2
ORDER BY 1, 2
`

type ReportDailyByCategoryParams struct {
	Bucket   interface{}
	Bucket_2 interface{}
}

type ReportDailyByCategoryRow struct {
	Period       interface{}
	UtilityClass string
	Consumption  int64
}

// Group by metering_point.utility_class (D-04: utility class = water | electricity).
func (q *Queries) ReportDailyByCategory(ctx context.Context, arg ReportDailyByCategoryParams) ([]ReportDailyByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportDailyByCategory, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportDailyByCategoryRow
	for rows.Next() {
		var i ReportDailyByCategoryRow
		if err := rows.Scan(&i.Period, &i.UtilityClass, &i.Consumption); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDailyByMP = `-- name: ReportDailyByMP :many

SELECT
  time_bucket('1 day', bucket) AS period,
  metering_point_id,
  round(coalesce(sum(cumulative_delta), 0))::bigint        AS consumption,
  sum(uplink_count)            AS uplinks,
  sum(flagged_count)           AS flagged
FROM measurement_hourly
WHERE metering_point_id = $1
  AND bucket >= $2 AND bucket < $3
GROUP BY 1, 2
ORDER BY 1
`

type ReportDailyByMPParams struct {
	MeteringPointID pgtype.UUID
	Bucket          interface{}
	Bucket_2        interface{}
}

type ReportDailyByMPRow struct {
	Period          interface{}
	MeteringPointID pgtype.UUID
	Consumption     int64
	Uplinks         int64
	Flagged         int64
}

// -------- DATA QUERIES ----------
// Daily report — sources measurement_hourly, buckets to days.
// Returns one row per (day, metering_point_id).
func (q *Queries) ReportDailyByMP(ctx context.Context, arg ReportDailyByMPParams) ([]ReportDailyByMPRow, error) {
	rows, err := q.db.Query(ctx, reportDailyByMP, arg.MeteringPointID, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportDailyByMPRow
	for rows.Next() {
		var i ReportDailyByMPRow
		if err := rows.Scan(
			&i.Period,
			&i.MeteringPointID,
			&i.Consumption,
			&i.Uplinks,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDailyBySite = `-- name: ReportDailyBySite :many
SELECT
  time_bucket('1 day', mh.bucket) AS period,
  mp.site_id,
  s.name                          AS site_name,
  round(coalesce(sum(mh.cumulative_delta), 0))::bigint        AS consumption
FROM measurement_hourly mh
JOIN metering_point mp ON mp.id = mh.metering_point_id
JOIN site s ON s.id = mp.site_id
WHERE mh.bucket >= $1 AND mh.bucket < $2
  AND ($3::UUID IS NULL OR mp.site_id = $3)
GROUP BY 1, 2, 3
ORDER BY 1, 3
`

type ReportDailyBySiteParams struct {
	Bucket   interface{}
	Bucket_2 interface{}
	Column3  pgtype.UUID
}

type ReportDailyBySiteRow struct {
	Period      interface{}
	SiteID      pgtype.UUID
	SiteName    string
	Consumption int64
}

func (q *Queries) ReportDailyBySite(ctx context.Context, arg ReportDailyBySiteParams) ([]ReportDailyBySiteRow, error) {
	rows, err := q.db.Query(ctx, reportDailyBySite, arg.Bucket, arg.Bucket_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportDailyBySiteRow
	for rows.Next() {
		var i ReportDailyBySiteRow
		if err := rows.Scan(
			&i.Period,
			&i.SiteID,
			&i.SiteName,
			&i.Consumption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportMonthlyByCategory = `-- name: ReportMonthlyByCategory :many
SELECT
  time_bucket('1 month', md.bucket) AS period,
  mp.utility_class,
  round(coalesce(sum(md.cumulative_delta), 0))::bigint AS consumption
FROM measurement_daily md
JOIN metering_point mp ON mp.id = md.metering_point_id
WHERE md.bucket >= $1 AND md.bucket < $2
GROUP BY 1, 2
ORDER BY 1, 2
`

type ReportMonthlyByCategoryParams struct {
	Bucket   interface{}
	Bucket_2 interface{}
}

type ReportMonthlyByCategoryRow struct {
	Period       interface{}
	UtilityClass string
	Consumption  int64
}

func (q *Queries) ReportMonthlyByCategory(ctx context.Context, arg ReportMonthlyByCategoryParams) ([]ReportMonthlyByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportMonthlyByCategory, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMonthlyByCategoryRow
	for rows.Next() {
		var i ReportMonthlyByCategoryRow
		if err := rows.Scan(&i.Period, &i.UtilityClass, &i.Consumption); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportMonthlyByMP = `-- name: ReportMonthlyByMP :many
SELECT
  time_bucket('1 month', bucket) AS period,
  metering_point_id,
  round(coalesce(sum(cumulative_delta), 0))::bigint AS consumption,
  sum(uplink_count) AS uplinks,
  sum(flagged_count) AS flagged
FROM measurement_daily
WHERE metering_point_id = $1
  AND bucket >= $2 AND bucket < $3
GROUP BY 1, 2
ORDER BY 1
`

type ReportMonthlyByMPParams struct {
	MeteringPointID pgtype.UUID
	Bucket          interface{}
	Bucket_2        interface{}
}

type ReportMonthlyByMPRow struct {
	Period          interface{}
	MeteringPointID pgtype.UUID
	Consumption     int64
	Uplinks         int64
	Flagged         int64
}

func (q *Queries) ReportMonthlyByMP(ctx context.Context, arg ReportMonthlyByMPParams) ([]ReportMonthlyByMPRow, error) {
	rows, err := q.db.Query(ctx, reportMonthlyByMP, arg.MeteringPointID, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMonthlyByMPRow
	for rows.Next() {
		var i ReportMonthlyByMPRow
		if err := rows.Scan(
			&i.Period,
			&i.MeteringPointID,
			&i.Consumption,
			&i.Uplinks,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportMonthlyBySite = `-- name: ReportMonthlyBySite :many
SELECT
  time_bucket('1 month', md.bucket) AS period,
  mp.site_id,
  s.name             AS site_name,
  round(coalesce(sum(md.cumulative_delta), 0))::bigint AS consumption
FROM measurement_daily md
JOIN metering_point mp ON mp.id = md.metering_point_id
JOIN site s ON s.id = mp.site_id
WHERE md.bucket >= $1 AND md.bucket < $2
  AND ($3::UUID IS NULL OR mp.site_id = $3)
GROUP BY 1, 2, 3
ORDER BY 1, 3
`

type ReportMonthlyBySiteParams struct {
	Bucket   interface{}
	Bucket_2 interface{}
	Column3  pgtype.UUID
}

type ReportMonthlyBySiteRow struct {
	Period      interface{}
	SiteID      pgtype.UUID
	SiteName    string
	Consumption int64
}

func (q *Queries) ReportMonthlyBySite(ctx context.Context, arg ReportMonthlyBySiteParams) ([]ReportMonthlyBySiteRow, error) {
	rows, err := q.db.Query(ctx, reportMonthlyBySite, arg.Bucket, arg.Bucket_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMonthlyBySiteRow
	for rows.Next() {
		var i ReportMonthlyBySiteRow
		if err := rows.Scan(
			&i.Period,
			&i.SiteID,
			&i.SiteName,
			&i.Consumption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportYearlyByCategory = `-- name: ReportYearlyByCategory :many
SELECT
  time_bucket('1 year', my.bucket) AS period,
  mp.utility_class,
  round(coalesce(sum(my.cumulative_delta), 0))::bigint AS consumption
FROM measurement_monthly my
JOIN metering_point mp ON mp.id = my.metering_point_id
WHERE my.bucket >= $1 AND my.bucket < $2
GROUP BY 1, 2
ORDER BY 1, 2
`

type ReportYearlyByCategoryParams struct {
	Bucket   interface{}
	Bucket_2 interface{}
}

type ReportYearlyByCategoryRow struct {
	Period       interface{}
	UtilityClass string
	Consumption  int64
}

func (q *Queries) ReportYearlyByCategory(ctx context.Context, arg ReportYearlyByCategoryParams) ([]ReportYearlyByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportYearlyByCategory, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportYearlyByCategoryRow
	for rows.Next() {
		var i ReportYearlyByCategoryRow
		if err := rows.Scan(&i.Period, &i.UtilityClass, &i.Consumption); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportYearlyByMP = `-- name: ReportYearlyByMP :many
SELECT
  time_bucket('1 year', bucket) AS period,
  metering_point_id,
  round(coalesce(sum(cumulative_delta), 0))::bigint AS consumption
FROM measurement_monthly
WHERE metering_point_id = $1
  AND bucket >= $2 AND bucket < $3
GROUP BY 1, 2
ORDER BY 1
`

type ReportYearlyByMPParams struct {
	MeteringPointID pgtype.UUID
	Bucket          interface{}
	Bucket_2        interface{}
}

type ReportYearlyByMPRow struct {
	Period          interface{}
	MeteringPointID pgtype.UUID
	Consumption     int64
}

func (q *Queries) ReportYearlyByMP(ctx context.Context, arg ReportYearlyByMPParams) ([]ReportYearlyByMPRow, error) {
	rows, err := q.db.Query(ctx, reportYearlyByMP, arg.MeteringPointID, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportYearlyByMPRow
	for rows.Next() {
		var i ReportYearlyByMPRow
		if err := rows.Scan(&i.Period, &i.MeteringPointID, &i.Consumption); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportYearlyBySite = `-- name: ReportYearlyBySite :many
SELECT
  time_bucket('1 year', my.bucket) AS period,
  mp.site_id,
  s.name             AS site_name,
  round(coalesce(sum(my.cumulative_delta), 0))::bigint AS consumption
FROM measurement_monthly my
JOIN metering_point mp ON mp.id = my.metering_point_id
JOIN site s ON s.id = mp.site_id
WHERE my.bucket >= $1 AND my.bucket < $2
  AND ($3::UUID IS NULL OR mp.site_id = $3)
GROUP BY 1, 2, 3
ORDER BY 1, 3
`

type ReportYearlyBySiteParams struct {
	Bucket   interface{}
	Bucket_2 interface{}
	Column3  pgtype.UUID
}

type ReportYearlyBySiteRow struct {
	Period      interface{}
	SiteID      pgtype.UUID
	SiteName    string
	Consumption int64
}

func (q *Queries) ReportYearlyBySite(ctx context.Context, arg ReportYearlyBySiteParams) ([]ReportYearlyBySiteRow, error) {
	rows, err := q.db.Query(ctx, reportYearlyBySite, arg.Bucket, arg.Bucket_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportYearlyBySiteRow
	for rows.Next() {
		var i ReportYearlyBySiteRow
		if err := rows.Scan(
			&i.Period,
			&i.SiteID,
			&i.SiteName,
			&i.Consumption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportPDFStatus = `-- name: UpdateReportPDFStatus :exec
UPDATE report SET pdf_status = $2, pdf_path = $3 WHERE id = $1
`

type UpdateReportPDFStatusParams struct {
	ID        pgtype.UUID
	PdfStatus string
	PdfPath   *string
}

func (q *Queries) UpdateReportPDFStatus(ctx context.Context, arg UpdateReportPDFStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportPDFStatus, arg.ID, arg.PdfStatus, arg.PdfPath)
	return err
}
