// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getRetentionConfig = `-- name: GetRetentionConfig :one

SELECT id, raw_days, hourly_days, daily_days, monthly_days, yearly_days, updated_at
FROM retention_config
WHERE id = 1
`

// internal/db/queries/settings.sql
// Retention configuration queries (DATA-13 / D-09 / Plan 05-11).
//
// The retention_config table is a singleton (id=1) seeded at install time
// by internal/install/finish.go. Queries here power the Settings → Data
// Retention card GET + PATCH handlers.
// Returns the singleton retention configuration row (id=1).
// Called by both GET /api/settings/retention (read) and the PATCH handler
// (to snapshot before-state for the audit diff).
func (q *Queries) GetRetentionConfig(ctx context.Context) (RetentionConfig, error) {
	row := q.db.QueryRow(ctx, getRetentionConfig)
	var i RetentionConfig
	err := row.Scan(
		&i.ID,
		&i.RawDays,
		&i.HourlyDays,
		&i.DailyDays,
		&i.MonthlyDays,
		&i.YearlyDays,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRetentionConfig = `-- name: UpdateRetentionConfig :one
UPDATE retention_config
SET raw_days     = COALESCE($1::integer, raw_days),
    hourly_days  = COALESCE($2::integer, hourly_days),
    daily_days   = COALESCE($3::integer, daily_days),
    monthly_days = COALESCE($4::integer, monthly_days),
    yearly_days  = $5::integer,
    updated_at   = now()
WHERE id = 1
RETURNING id, raw_days, hourly_days, daily_days, monthly_days, yearly_days, updated_at
`

type UpdateRetentionConfigParams struct {
	RawDays     *int32
	HourlyDays  *int32
	DailyDays   *int32
	MonthlyDays *int32
	YearlyDays  *int32
}

// Partial update via COALESCE: only fields whose $N is non-NULL are changed.
// yearly_days is NOT wrapped in COALESCE — the handler passes the resolved
// value explicitly (including NULL to express "forever"), using a sentinel
// flag to distinguish "omitted" from "explicitly set to null". See Plan 05-11
// doc.go for the sentinel protocol.
//
// $1..4 are nullable integers (sqlc maps *int32). Passing nil = COALESCE keeps
// the existing value. $5 yearly_days is always explicit (nil = forever).
func (q *Queries) UpdateRetentionConfig(ctx context.Context, arg UpdateRetentionConfigParams) (RetentionConfig, error) {
	row := q.db.QueryRow(ctx, updateRetentionConfig,
		arg.RawDays,
		arg.HourlyDays,
		arg.DailyDays,
		arg.MonthlyDays,
		arg.YearlyDays,
	)
	var i RetentionConfig
	err := row.Scan(
		&i.ID,
		&i.RawDays,
		&i.HourlyDays,
		&i.DailyDays,
		&i.MonthlyDays,
		&i.YearlyDays,
		&i.UpdatedAt,
	)
	return i, err
}
