// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRetentionConfig = `-- name: GetRetentionConfig :one

SELECT id, raw_days, hourly_days, daily_days, monthly_days, yearly_days,
       alerts_days, audit_log_days,
       backup_warn_threshold_hours, backup_crit_threshold_hours,
       updated_at
FROM retention_config
WHERE id = 1
`

type GetRetentionConfigRow struct {
	ID                       int32
	RawDays                  int32
	HourlyDays               int32
	DailyDays                int32
	MonthlyDays              int32
	YearlyDays               *int32
	AlertsDays               int32
	AuditLogDays             int32
	BackupWarnThresholdHours int32
	BackupCritThresholdHours int32
	UpdatedAt                pgtype.Timestamptz
}

// internal/db/queries/settings.sql
// Retention configuration queries (DATA-13 / D-09 / Plan 05-11).
//
// The retention_config table is a singleton (id=1) seeded at install time
// by internal/install/finish.go. Queries here power the Settings → Data
// Retention card GET + PATCH handlers.
// Returns the singleton retention configuration row (id=1).
// Called by both GET /api/settings/retention (read) and the PATCH handler
// (to snapshot before-state for the audit diff).
//
// Phase 6 Plan 06-02 schema-bridge fix: explicitly enumerate every column
// so that adding new columns (alerts_days / audit_log_days from 0040,
// future v2 fields) keeps the sqlc-generated row type aligned with the
// table type. sqlc emits the canonical `RetentionConfig` struct when the
// SELECT column set matches the table 1:1; otherwise it generates a
// per-query row alias that breaks downstream code expecting the table type.
func (q *Queries) GetRetentionConfig(ctx context.Context) (GetRetentionConfigRow, error) {
	row := q.db.QueryRow(ctx, getRetentionConfig)
	var i GetRetentionConfigRow
	err := row.Scan(
		&i.ID,
		&i.RawDays,
		&i.HourlyDays,
		&i.DailyDays,
		&i.MonthlyDays,
		&i.YearlyDays,
		&i.AlertsDays,
		&i.AuditLogDays,
		&i.BackupWarnThresholdHours,
		&i.BackupCritThresholdHours,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRetentionConfig = `-- name: UpdateRetentionConfig :one
UPDATE retention_config
SET raw_days      = COALESCE($1::integer, raw_days),
    hourly_days   = COALESCE($2::integer, hourly_days),
    daily_days    = COALESCE($3::integer, daily_days),
    monthly_days  = COALESCE($4::integer, monthly_days),
    yearly_days   = $5::integer,
    alerts_days   = COALESCE($6::integer, alerts_days),
    audit_log_days = COALESCE($7::integer, audit_log_days),
    updated_at    = now()
WHERE id = 1
RETURNING id, raw_days, hourly_days, daily_days, monthly_days, yearly_days,
          alerts_days, audit_log_days, updated_at
`

type UpdateRetentionConfigParams struct {
	RawDays      *int32
	HourlyDays   *int32
	DailyDays    *int32
	MonthlyDays  *int32
	YearlyDays   *int32
	AlertsDays   *int32
	AuditLogDays *int32
}

type UpdateRetentionConfigRow struct {
	ID           int32
	RawDays      int32
	HourlyDays   int32
	DailyDays    int32
	MonthlyDays  int32
	YearlyDays   *int32
	AlertsDays   int32
	AuditLogDays int32
	UpdatedAt    pgtype.Timestamptz
}

// Partial update via COALESCE: only fields whose $N is non-NULL are changed.
// yearly_days is NOT wrapped in COALESCE — the handler passes the resolved
// value explicitly (including NULL to express "forever"), using a sentinel
// flag to distinguish "omitted" from "explicitly set to null". See Plan 05-11
// doc.go for the sentinel protocol.
//
// Phase 6 Plan 06-10: alerts_days and audit_log_days added. Both use COALESCE
// (omitting them from PATCH preserves the existing value). The Phase 5
// TimescaleDB policy reconciliation does NOT apply to alerts/audit_log — those
// tables are NOT hypertables; their retention is enforced by the alerts-prune
// worker (Plan 06-11 task 1) and the AuditPruneWorker (Plan 06-01). The
// config row is the sole source of truth; the workers read it on each run.
func (q *Queries) UpdateRetentionConfig(ctx context.Context, arg UpdateRetentionConfigParams) (UpdateRetentionConfigRow, error) {
	row := q.db.QueryRow(ctx, updateRetentionConfig,
		arg.RawDays,
		arg.HourlyDays,
		arg.DailyDays,
		arg.MonthlyDays,
		arg.YearlyDays,
		arg.AlertsDays,
		arg.AuditLogDays,
	)
	var i UpdateRetentionConfigRow
	err := row.Scan(
		&i.ID,
		&i.RawDays,
		&i.HourlyDays,
		&i.DailyDays,
		&i.MonthlyDays,
		&i.YearlyDays,
		&i.AlertsDays,
		&i.AuditLogDays,
		&i.UpdatedAt,
	)
	return i, err
}
