// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSite = `-- name: ArchiveSite :one
UPDATE site SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at
`

// D-20 soft-delete. Idempotent guard `archived_at IS NULL` — re-archiving an
// already-archived site returns no row (caller treats as no-op).
func (q *Queries) ArchiveSite(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, archiveSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SiteType,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.Address,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMPsOnSite = `-- name: CountMPsOnSite :one
SELECT count(*) FROM metering_point WHERE site_id = $1 AND archived_at IS NULL
`

// Site detail header badge "N metering points". Used by Plan 02-08 site detail
// page; counts only active MPs (D-20 — archived MPs hide from default views).
func (q *Queries) CountMPsOnSite(ctx context.Context, siteID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMPsOnSite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSite = `-- name: CreateSite :one

INSERT INTO site (parent_id, name, site_type, lat, lng, timezone, address, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at
`

type CreateSiteParams struct {
	ParentID    pgtype.UUID
	Name        string
	SiteType    *string
	Lat         *float64
	Lng         *float64
	Timezone    string
	Address     *string
	Description *string
}

// Site (D-17 + D-20) — physical/logical hierarchy anchor for metering points
// and devices. Soft-deleted via archived_at; hard delete blocked by FKs from
// metering_point and (transitively) binding.
// Plan 02-08 site dialog. Caller resolves parent_id from the parent picker
// (NULL for top-level sites). timezone is required (D-17 — every site has
// one; UI defaults to install timezone).
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ParentID,
		arg.Name,
		arg.SiteType,
		arg.Lat,
		arg.Lng,
		arg.Timezone,
		arg.Address,
		arg.Description,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SiteType,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.Address,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at FROM site WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SiteType,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.Address,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSites = `-- name: ListActiveSites :many
SELECT id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at FROM site WHERE archived_at IS NULL ORDER BY name ASC
`

// Site list page (D-20). archived_at IS NULL filter hits the partial index.
func (q *Queries) ListActiveSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listActiveSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.SiteType,
			&i.Lat,
			&i.Lng,
			&i.Timezone,
			&i.Address,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedSites = `-- name: ListArchivedSites :many
SELECT id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at FROM site WHERE archived_at IS NOT NULL ORDER BY archived_at DESC
`

// Archive view (D-20) — sorted most-recently-archived first so admins see
// their last action at the top.
func (q *Queries) ListArchivedSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listArchivedSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.SiteType,
			&i.Lat,
			&i.Lng,
			&i.Timezone,
			&i.Address,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildSites = `-- name: ListChildSites :many
SELECT id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at FROM site WHERE parent_id = $1 AND archived_at IS NULL ORDER BY name ASC
`

// Site detail page sub-section: direct children only (one level), so the
// breadcrumb expands lazily rather than fetching the whole subtree.
func (q *Queries) ListChildSites(ctx context.Context, parentID pgtype.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listChildSites, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.SiteType,
			&i.Lat,
			&i.Lng,
			&i.Timezone,
			&i.Address,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSite = `-- name: RestoreSite :one
UPDATE site SET archived_at = NULL
WHERE id = $1 AND archived_at IS NOT NULL
RETURNING id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at
`

// D-20 restore from archive view. Symmetric guard.
func (q *Queries) RestoreSite(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, restoreSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SiteType,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.Address,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSite = `-- name: UpdateSite :one
UPDATE site SET
    name = $2, site_type = $3, lat = $4, lng = $5,
    timezone = $6, address = $7, description = $8
WHERE id = $1
RETURNING id, parent_id, name, site_type, lat, lng, timezone, address, description, archived_at, created_at, updated_at
`

type UpdateSiteParams struct {
	ID          pgtype.UUID
	Name        string
	SiteType    *string
	Lat         *float64
	Lng         *float64
	Timezone    string
	Address     *string
	Description *string
}

// Plan 02-08 site edit dialog. parent_id intentionally NOT updatable here —
// moving a site between parents is a separate "reparent" flow with audit
// implications and is deferred to Phase 6.
func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite,
		arg.ID,
		arg.Name,
		arg.SiteType,
		arg.Lat,
		arg.Lng,
		arg.Timezone,
		arg.Address,
		arg.Description,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SiteType,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.Address,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
