// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeseries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardTimeseries = `-- name: DashboardTimeseries :many

WITH deltas AS (
    SELECT
        time_bucket($1::interval, m.time) AS bucket,
        m.cumulative_value - LAG(m.cumulative_value) OVER (
            PARTITION BY m.metering_point_id ORDER BY m.time
        ) AS row_delta
    FROM measurement m
    INNER JOIN metering_point mp ON mp.id = m.metering_point_id
    WHERE mp.utility_class = $2
      AND mp.archived_at IS NULL
      AND m.time >= $3
      AND m.time < $4
)
SELECT
    bucket,
    COALESCE(SUM(row_delta), 0)::numeric AS cumulative_delta
FROM deltas
GROUP BY bucket
ORDER BY bucket
`

type DashboardTimeseriesParams struct {
	BucketInterval pgtype.Interval
	UtilityClass   string
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
}

type DashboardTimeseriesRow struct {
	Bucket          interface{}
	CumulativeDelta pgtype.Numeric
}

// Time-series chart queries — D-12 bucket schedule implemented in handler.
//
// DashboardTimeseries: cross-MP aggregate for the dashboard consumption chart
//
//	(GET /api/dashboard/timeseries). The handler picks bucket interval per D-12
//	schedule:
//
//	| range        | bucket_interval |
//	|--------------|-----------------|
//	| today        | 5 minutes       |
//	| 24h          | 5 minutes       |
//	| 7d           | 1 hour          |
//	| 30d          | 4 hours         |
//	| custom ≤ 30d | 1 hour          |
//	| custom > 30d | 1 day           |
//
// MeteringPointTimeseries: per-MP detail (Plan 05/09 consume).
// D-12: time_bucket() with handler-controlled interval. Aggregates cumulative
// delta across all MPs of the given utility_class.
//
// The LAG window function computes the per-row delta in a CTE; the outer query
// then SUMs those deltas per time_bucket. This two-step pattern is required
// because Postgres forbids aggregate functions that contain window function
// calls directly (SQLSTATE 42803).
//
// sqlc.arg(utility_class), sqlc.arg(start_time), sqlc.arg(end_time), sqlc.arg(bucket_interval)
func (q *Queries) DashboardTimeseries(ctx context.Context, arg DashboardTimeseriesParams) ([]DashboardTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardTimeseries,
		arg.BucketInterval,
		arg.UtilityClass,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTimeseriesRow
	for rows.Next() {
		var i DashboardTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.CumulativeDelta); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meteringPointTimeseries = `-- name: MeteringPointTimeseries :many
SELECT
    time_bucket($1::interval, time) AS bucket,
    AVG(cumulative_value)::numeric AS cumulative_avg,
    AVG(instant_value)::numeric AS instant_avg,
    AVG(battery_pct)::numeric AS battery_avg,
    AVG(rssi)::numeric AS rssi_avg,
    AVG(snr)::numeric AS snr_avg
FROM measurement
WHERE metering_point_id = $2
  AND time >= $3
  AND time < $4
GROUP BY bucket
ORDER BY bucket
`

type MeteringPointTimeseriesParams struct {
	BucketInterval  pgtype.Interval
	MeteringPointID pgtype.UUID
	StartTime       pgtype.Timestamptz
	EndTime         pgtype.Timestamptz
}

type MeteringPointTimeseriesRow struct {
	Bucket        interface{}
	CumulativeAvg pgtype.Numeric
	InstantAvg    pgtype.Numeric
	BatteryAvg    pgtype.Numeric
	RssiAvg       pgtype.Numeric
	SnrAvg        pgtype.Numeric
}

// For per-MP detail page (Plan 05/09 consume).
// sqlc.arg(metering_point_id), sqlc.arg(start_time), sqlc.arg(end_time), sqlc.arg(bucket_interval)
func (q *Queries) MeteringPointTimeseries(ctx context.Context, arg MeteringPointTimeseriesParams) ([]MeteringPointTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, meteringPointTimeseries,
		arg.BucketInterval,
		arg.MeteringPointID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeteringPointTimeseriesRow
	for rows.Next() {
		var i MeteringPointTimeseriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.CumulativeAvg,
			&i.InstantAvg,
			&i.BatteryAvg,
			&i.RssiAvg,
			&i.SnrAvg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
