// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uplinks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUplinksByMP = `-- name: ListUplinksByMP :many

SELECT
    time, cumulative_value, instant_value,
    battery_pct, rssi, snr, fcnt, quality,
    raw_payload, decoded_object
FROM measurement
WHERE metering_point_id = $1
  AND time < COALESCE($3::timestamptz, 'infinity'::timestamptz)
  AND (
      $4::text[] IS NULL
      OR cardinality($4::text[]) = 0
      OR quality = ANY($4::text[])
  )
ORDER BY time DESC
LIMIT $2
`

type ListUplinksByMPParams struct {
	MeteringPointID pgtype.UUID
	Limit           int32
	Column3         pgtype.Timestamptz
	Column4         []string
}

type ListUplinksByMPRow struct {
	Time            pgtype.Timestamptz
	CumulativeValue pgtype.Numeric
	InstantValue    pgtype.Numeric
	BatteryPct      *int16
	Rssi            *int16
	Snr             *float32
	Fcnt            *int32
	Quality         string
	RawPayload      []byte
	DecodedObject   []byte
}

// uplinks.sql — DETL-02 cursor-paginated uplink log for the per-MP uplinks tab.
//
// ListUplinksByMP uses (metering_point_id, time DESC) index for the no-filter
// case and the partial index measurement_quality_flagged_idx for flagged-only
// queries. Cursor is on time DESC so result pages are stable even as new rows
// insert (unlike OFFSET which shifts under concurrent ingest).
//
// QualitySummaryByMP computes the D-19 "X of last 100 uplinks flagged" badge:
// the inner sub-select limits to 100 rows, the outer groups by quality value.
// DETL-02: cursor-paginated, time DESC, optional quality filter.
// Index path: measurement_mp_time_idx (metering_point_id, time DESC).
// $1 = mp_id, $2 = limit (<=500), $3 = before (nullable timestamptz cursor),
// $4 = quality filter (TEXT[]; NULL or empty = no filter).
func (q *Queries) ListUplinksByMP(ctx context.Context, arg ListUplinksByMPParams) ([]ListUplinksByMPRow, error) {
	rows, err := q.db.Query(ctx, listUplinksByMP,
		arg.MeteringPointID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUplinksByMPRow
	for rows.Next() {
		var i ListUplinksByMPRow
		if err := rows.Scan(
			&i.Time,
			&i.CumulativeValue,
			&i.InstantValue,
			&i.BatteryPct,
			&i.Rssi,
			&i.Snr,
			&i.Fcnt,
			&i.Quality,
			&i.RawPayload,
			&i.DecodedObject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qualitySummaryByMP = `-- name: QualitySummaryByMP :many
SELECT quality, COUNT(*)::bigint AS count
FROM (
    SELECT quality FROM measurement
    WHERE metering_point_id = $1
    ORDER BY time DESC
    LIMIT 100
) recent
GROUP BY quality
`

type QualitySummaryByMPRow struct {
	Quality string
	Count   int64
}

// D-19: window of last 100 uplinks, grouped by quality.
// Returns one row per quality value present in the window.
func (q *Queries) QualitySummaryByMP(ctx context.Context, meteringPointID pgtype.UUID) ([]QualitySummaryByMPRow, error) {
	rows, err := q.db.Query(ctx, qualitySummaryByMP, meteringPointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualitySummaryByMPRow
	for rows.Next() {
		var i QualitySummaryByMPRow
		if err := rows.Scan(&i.Quality, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
