// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS(
    SELECT 1 FROM "user"
    WHERE role = 'admin'
      AND disabled_at IS NULL
) AS exists
`

// Plan 14 first-run gate: returns TRUE if at least one enabled admin exists.
func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, adminExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, must_change_password, disabled_at, created_at, updated_at, last_login_at FROM "user"
WHERE email = $1
  AND disabled_at IS NULL
`

// Plan 09 (login). Email must already be lower()'d by the caller — the
// 0002_users CHECK enforces it but we don't want to lose the index hit.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :one
INSERT INTO "user" (email, name, password_hash, role, must_change_password)
VALUES ($1, $2, $3, 'admin', FALSE)
RETURNING id, email, name, role, created_at
`

type InsertAdminUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

type InsertAdminUserRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
}

// Plan 15 install wizard finish — creates the bootstrap admin atomically with
// the rest of the wizard commit.
func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (InsertAdminUserRow, error) {
	row := q.db.QueryRow(ctx, insertAdminUser, arg.Email, arg.Name, arg.PasswordHash)
	var i InsertAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE "user"
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

// Plan 11 account UI: change-password flow.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
