-- Audit Log (D-22 + D-23 + D-24 + AUDIT-01). The audit_log table is
-- INSERT-ONLY at the DB layer (0016 trigger raises `audit_log is INSERT-ONLY`
-- on UPDATE / DELETE — T-02-04-02 mitigation). Every state-changing action on
-- Site, Metering Point, Device, Device Profile, and Binding writes a row
-- here in the SAME transaction as the domain mutation (D-23, Pitfall 7).
--
-- Plan 02-08 wraps WriteAuditLog in `internal/audit/log.go` with an Entry
-- struct + audit.WriteEntry(ctx, tx, entry) helper that takes a pgx.Tx
-- (NOT a Pool) — call sites pass the same tx the domain mutation uses so
-- the audit row commits atomically with the change it describes.

-- name: WriteAuditLog :exec
-- D-22 + D-23: 8 caller-provided fields (id auto-generated by
-- gen_random_uuid() default, time auto by now() default).
-- The CHECK constraints enforce D-22 vocabulary at the DB layer:
--   action ∈ {create, update, archive, restore, swap, decommission,
--             profile_create, profile_update, binding_open, binding_close,
--             rollover_detected}
--   entity_type ∈ {site, metering_point, device, device_profile, binding}
-- An action / entity_type outside these sets raises 23514 (check_violation)
-- with the named CHECK constraint in the error — caller treats as a bug.
INSERT INTO audit_log (
    user_id, action, entity_type, entity_id,
    before, after, notes, request_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8);

-- name: GetAuditEntry :one
-- Test-only in Phase 2 (the round-trip assertion in measurements_test.go's
-- audit sibling). Phase 6 audit browse will use ListAuditEntriesByEntity +
-- pagination instead.
SELECT * FROM audit_log WHERE id = $1;

-- name: ListAuditEntriesByEntity :many
-- Phase 6 audit browse with entity filter ("show me everything that ever
-- happened to MP <id>"). Phase 2 ships the query so internal tests can
-- assert WriteEntry actually persisted what was claimed. Bounded by LIMIT/
-- OFFSET so a UI can't accidentally page through years of audit rows.
SELECT * FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY time DESC
LIMIT $3 OFFSET $4;

-- name: ListAuditEntriesByUser :many
-- Phase 6 "all actions by Alice" browse. The (user_id, time DESC) index
-- (0016) covers this directly.
SELECT * FROM audit_log
WHERE user_id = $1
ORDER BY time DESC
LIMIT $2 OFFSET $3;

-- name: CountAuditEntriesByAction :one
-- Phase 6 metrics tile + Phase 2 tests. Time-bounded so the tile can show
-- "X swaps in the last 7 days" without scanning the whole table.
SELECT count(*) FROM audit_log WHERE action = $1 AND time >= $2;
