-- 0024_river_tables.up.sql
-- River v0.36.0 job-queue schema, embedded into golang-migrate so the install
-- runs a single migration tool (Pitfall #8 mitigation per 05-RESEARCH).
--
-- Generated by capturing `river migrate-up --line main` against a clean Postgres 16
-- and converting to idempotent CREATE … IF NOT EXISTS form.
-- Verified with pg_dump -s from postgres:16-alpine.
--
-- DO NOT hand-edit. To upgrade River:
--   1. Bump river versions in go.mod
--   2. Re-run the capture procedure documented in 05-01-PLAN.md Task 2
--   3. Land the diff as 0025_river_vX_upgrade.up.sql (NOT this file)

-- Type: river_job_state
DO $$ BEGIN
    CREATE TYPE river_job_state AS ENUM (
        'available',
        'cancelled',
        'completed',
        'discarded',
        'pending',
        'retryable',
        'running',
        'scheduled'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Function: river_job_state_in_bitmask (used by unique_idx partial index)
CREATE OR REPLACE FUNCTION river_job_state_in_bitmask(bitmask bit, state river_job_state)
  RETURNS boolean
  LANGUAGE sql
  IMMUTABLE
AS $function$
    SELECT CASE state
        WHEN 'available' THEN get_bit(bitmask, 7)
        WHEN 'cancelled' THEN get_bit(bitmask, 6)
        WHEN 'completed' THEN get_bit(bitmask, 5)
        WHEN 'discarded' THEN get_bit(bitmask, 4)
        WHEN 'pending'   THEN get_bit(bitmask, 3)
        WHEN 'retryable' THEN get_bit(bitmask, 2)
        WHEN 'running'   THEN get_bit(bitmask, 1)
        WHEN 'scheduled' THEN get_bit(bitmask, 0)
        ELSE 0
    END = 1;
$function$;

-- Table: river_migration (schema version tracking)
CREATE TABLE IF NOT EXISTS river_migration (
    line text NOT NULL,
    version bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT river_migration_pkey1 PRIMARY KEY (line, version),
    CONSTRAINT line_length CHECK ((char_length(line) > 0) AND (char_length(line) < 128)),
    CONSTRAINT version_gte_1 CHECK (version >= 1)
);

-- Sequence for river_job.id (created before the table so DEFAULT can reference it)
CREATE SEQUENCE IF NOT EXISTS river_job_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Table: river_job (primary job store — regular table, NOT UNLOGGED for durability)
CREATE TABLE IF NOT EXISTS river_job (
    id bigint NOT NULL DEFAULT nextval('river_job_id_seq'),
    state river_job_state NOT NULL DEFAULT 'available'::river_job_state,
    attempt smallint NOT NULL DEFAULT 0,
    max_attempts smallint NOT NULL,
    attempted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    finalized_at timestamptz,
    scheduled_at timestamptz NOT NULL DEFAULT now(),
    priority smallint NOT NULL DEFAULT 1,
    args jsonb NOT NULL,
    attempted_by text[],
    errors jsonb[],
    kind text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}',
    queue text NOT NULL DEFAULT 'default',
    tags varchar(255)[] NOT NULL DEFAULT '{}',
    unique_key bytea,
    unique_states bit(8),
    CONSTRAINT river_job_pkey PRIMARY KEY (id),
    CONSTRAINT finalized_or_finalized_at_null CHECK (
        (finalized_at IS NULL AND state <> ALL(ARRAY['cancelled'::river_job_state, 'completed'::river_job_state, 'discarded'::river_job_state]))
        OR
        (finalized_at IS NOT NULL AND state = ANY(ARRAY['cancelled'::river_job_state, 'completed'::river_job_state, 'discarded'::river_job_state]))
    ),
    CONSTRAINT kind_length CHECK ((char_length(kind) > 0) AND (char_length(kind) < 128)),
    CONSTRAINT max_attempts_is_positive CHECK (max_attempts > 0),
    CONSTRAINT priority_in_range CHECK (priority >= 1 AND priority <= 4),
    CONSTRAINT queue_length CHECK ((char_length(queue) > 0) AND (char_length(queue) < 128))
);

-- Owned-by link for the sequence (idempotent via DO block)
DO $$ BEGIN
    ALTER SEQUENCE river_job_id_seq OWNED BY river_job.id;
EXCEPTION
    WHEN undefined_object THEN NULL;
    WHEN duplicate_object THEN NULL;
END $$;

-- Table: river_leader (distributed leadership election — UNLOGGED for performance)
CREATE UNLOGGED TABLE IF NOT EXISTS river_leader (
    elected_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    leader_id text NOT NULL,
    name text NOT NULL DEFAULT 'default',
    CONSTRAINT river_leader_pkey PRIMARY KEY (name),
    CONSTRAINT leader_id_length CHECK ((char_length(leader_id) > 0) AND (char_length(leader_id) < 128)),
    CONSTRAINT name_length CHECK (name = 'default')
);

-- Table: river_queue (named queues — regular table)
CREATE TABLE IF NOT EXISTS river_queue (
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}',
    paused_at timestamptz,
    updated_at timestamptz NOT NULL,
    CONSTRAINT river_queue_pkey PRIMARY KEY (name)
);

-- Table: river_client (connected workers — UNLOGGED for performance)
CREATE UNLOGGED TABLE IF NOT EXISTS river_client (
    id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}',
    paused_at timestamptz,
    updated_at timestamptz NOT NULL,
    CONSTRAINT river_client_pkey PRIMARY KEY (id),
    CONSTRAINT name_length CHECK ((char_length(id) > 0) AND (char_length(id) < 128))
);

-- Table: river_client_queue (per-worker queue metrics — UNLOGGED)
CREATE UNLOGGED TABLE IF NOT EXISTS river_client_queue (
    river_client_id text NOT NULL,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    max_workers bigint NOT NULL DEFAULT 0,
    metadata jsonb NOT NULL DEFAULT '{}',
    num_jobs_completed bigint NOT NULL DEFAULT 0,
    num_jobs_running bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL,
    CONSTRAINT river_client_queue_pkey PRIMARY KEY (river_client_id, name),
    CONSTRAINT name_length CHECK ((char_length(name) > 0) AND (char_length(name) < 128)),
    CONSTRAINT num_jobs_completed_zero_or_positive CHECK (num_jobs_completed >= 0),
    CONSTRAINT num_jobs_running_zero_or_positive CHECK (num_jobs_running >= 0),
    CONSTRAINT river_client_queue_river_client_id_fkey FOREIGN KEY (river_client_id) REFERENCES river_client(id) ON DELETE CASCADE
);

-- Indexes on river_job
CREATE INDEX IF NOT EXISTS river_job_args_index ON river_job USING gin (args);
CREATE INDEX IF NOT EXISTS river_job_kind ON river_job USING btree (kind);
CREATE INDEX IF NOT EXISTS river_job_metadata_index ON river_job USING gin (metadata);
CREATE INDEX IF NOT EXISTS river_job_prioritized_fetching_index ON river_job USING btree (state, queue, priority, scheduled_at, id);
CREATE INDEX IF NOT EXISTS river_job_state_and_finalized_at_index ON river_job USING btree (state, finalized_at) WHERE (finalized_at IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS river_job_unique_idx ON river_job USING btree (unique_key)
    WHERE (unique_key IS NOT NULL AND unique_states IS NOT NULL AND river_job_state_in_bitmask(unique_states, state));

-- Seed migration version records (River v0.36 schema version = 6)
INSERT INTO river_migration (line, version)
    VALUES ('main', 1), ('main', 2), ('main', 3), ('main', 4), ('main', 5), ('main', 6)
    ON CONFLICT (line, version) DO NOTHING;
