import { defineConfig, devices } from "@playwright/test";

// Shifter Playwright config.
//
// Layout:
//   web/playwright/specs/      — *.spec.ts files
//   web/playwright/fixtures/   — storageState JSON (admin-session.json,
//                                viewer-session.json) regenerated by
//                                `pnpm exec playwright open --save-storage`
//                                against a seeded dev server (Wave 4 task).
//
// Three projects:
//   - chromium  : unauthenticated baseline (login flows, public pages)
//   - admin     : pre-authenticated as the seeded admin user
//   - viewer    : pre-authenticated as a viewer (RBAC negative tests)
//
// baseURL targets the Go server's :8080 (the Go binary serves the Vite-built
// SPA in production; local dev is `cd web && pnpm dev` on :5173 with proxy).
// Override via PLAYWRIGHT_BASE_URL when needed.
export default defineConfig({
  testDir: "./playwright/specs",
  reporter: "html",
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:8080",
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"], storageState: undefined },
    },
    {
      name: "admin",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "./playwright/fixtures/admin-session.json",
      },
    },
    {
      name: "viewer",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "./playwright/fixtures/viewer-session.json",
      },
    },
  ],
});
